<?php $carouselId = uniqid('carousel'); ?>
<div class="widget-carousel clearfix">
    <div id="<?php echo $carouselId; ?>" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
            <?php $i = 0; ?>
            <?php foreach ($block['resources'] as $story) { ?>
                <li data-target="#<?php echo $carouselId; ?>"
                    data-slide-to="<?php echo $i; ?>"<?php if ($i == 1) {
                    echo ' class="active"';
                } ?>></li>
                <?php $i++; ?>
            <?php } ?>
        </ol>
        <div class="carousel-inner">
            <?php $i = 1; ?>
            <?php foreach ($block['resources'] as $story) { ?>
                <?php $largeUrl = Pi::api('doc', 'media')->getSingleLinkUrl($story['main_image'])->setConfigModule('news')->thumb('large'); ?>
                <div class="h-entry carousel-item<?php if ($i == 1) {
                    echo ' active';
                } ?>" itemscope itemtype="https://schema.org/Article">
                    <a itemprop="url" class="u-url" href="<?php echo $this->escape($story['storyUrl']); ?>"
                       title="<?php echo $this->escape($story['title']); ?>">
                        <img itemprop="image" src="<?php echo $this->escape($largeUrl); ?>"
                             alt="<?php echo $this->escape($story['title']); ?>"
                             class="img-fluid u-photo d-block"/>
                    </a>

                    <div class="carousel-caption">
                        <h4 class="p-name" itemprop="name headline">
                            <a itemprop="url" class="u-url" href="<?php echo $this->escape($story['storyUrl']); ?>"
                               title="<?php echo $this->escape($story['title']); ?>">
                                <?php if ($story['important']) { ?> <span class="badge badge-danger"><?php echo _b('Important'); ?></span> <?php } ?>
                                <?php echo $this->escape($story['title']); ?>
                            </a>
                        </h4>
                        <ul class="text-muted list-inline">
                            <?php if ($block['showdate']) { ?>
                                <li class="list-inline-item dt-published">
                                    <i class="fas fa-calendar-alt"></i> <?php echo $this->escape($story['time_publish_view']); ?>
                                </li>
                            <?php } ?>
                            <?php if ($block['showhits']) { ?>
                                <li class="list-inline-item">
                                    <i class="far fa-eye"></i> <?php echo _number($this->escape($story['hits'])); ?>
                                </li>
                            <?php } ?>
                            <?php if ($block['showauthor']) { ?>
                                <?php foreach ($story['authors'] as $author) { ?>
                                    <li class="list-inline-item">
                                        <i class="fas fa-user"></i> <?php echo $author['authorRole']; ?> :
                                        <a title="<?php echo $author['authorName']; ?>"
                                           href="<?php echo $author['authorUrl']; ?>">
                                            <?php echo $author['authorName']; ?>
                                        </a>
                                    </li>
                                <?php } ?>
                            <?php } ?>
                        </ul>
                        <?php if ($block['showdesc']) { ?>
                            <div class="widget-summary p-summary"><?php echo $story['text_summary']; ?></div>
                        <?php } ?>
                        <meta itemprop="datePublished" content="<?php echo $this->escape(date("Y-m-d H:i:s", $story['time_publish'])); ?>"/>
                    </div>
                </div>
                <?php $i++; ?>
            <?php } ?>
            <a class="carousel-control-prev" href="#<?php echo $carouselId; ?>" role="button" data-slide="prev">
                <span class="carousel-control-prev-icon" aria-hidden="true"></span>
                <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#<?php echo $carouselId; ?>" role="button" data-slide="next">
                <span class="carousel-control-next-icon" aria-hidden="true"></span>
                <span class="sr-only">Next</span>
            </a>
        </div>
    </div>
</div>
