<div class="widget-list clearfix" itemscope itemtype="https://schema.org/ItemList">
    <ul class="list-unstyled">
        <?php foreach ($block['resources'] as $story) { ?>
            <li class="h-entry" itemscope itemtype="https://schema.org/Article" itemprop="itemListElement">
			    <span class="itemTitle p-name" itemprop="name">
				    <a itemprop="url" href="<?php echo $this->escape($story['storyUrl']); ?>" title="<?php echo $this->escape($story['title']); ?>">
                        <?php if ($story['important']) { ?> <span class="badge badge-danger"><?php echo _b('Important'); ?></span> <?php } ?>
                        <?php echo $this->escape($story['title']); ?>
                    </a>
			    </span>
                <?php if ($block['showdate']) { ?>
                    <span class="itemPostDate dt-published text-muted small">
				        <i class="fas fa-calendar-alt"></i> <?php echo $this->escape($story['time_publish_view']); ?>
                    </span>
                <?php } ?>
                <?php if ($block['showhits']) { ?>
                    <span class="itemStats text-muted small">
				        <i class="far fa-eye"></i> <?php echo $this->escape($story['hits']); ?>
			        </span>
                <?php } ?>
            </li>
        <?php } ?>
    </ul>
</div>
