<div class="widget-compressed clearfix">
    <?php $firstStory = array_shift($block['resources']); ?>
    <?php $mediumUrl = Pi::api('doc', 'media')->getSingleLinkUrl($firstStory['main_image'])->setConfigModule('news')->thumb('medium'); ?>
    <div class="card border-light widget-compressed-main h-entry clearfix mb-3" itemscope itemtype="https://schema.org/Article">
        <a itemprop="url" class="u-url"
           href="<?php echo $this->escape($firstStory['storyUrl']); ?>"
           title="<?php echo $this->escape($firstStory['title']); ?>">
            <img itemprop="image" src="<?php echo $this->escape($mediumUrl); ?>"
                 alt="<?php echo $this->escape($firstStory['title']); ?>"
                 class="img-fluid u-photo card-img-top"/>
        </a>
        <div class="card-body">
            <h3 class="p-name card-title" itemprop="name headline">
                <a itemprop="url" href="<?php echo $this->escape($firstStory['storyUrl']); ?>"
                   title="<?php echo $this->escape($firstStory['title']); ?>">
                    <?php echo $this->escape($firstStory['title']); ?>
                </a>
            </h3>
            <div class="card-text">
                <?php if ($block['showdate'] || $block['showhits'] || $block['showauthor']) { ?>
                    <ul class="text-muted list-inline">
                        <?php if ($block['showdate']) { ?>
                            <li class="list-inline-item dt-published">
                                <i class="fas fa-calendar-alt"></i> <?php echo $this->escape($firstStory['time_publish_view']); ?>
                            </li>
                        <?php } ?>
                        <?php if ($block['showhits']) { ?>
                            <li class="list-inline-item">
                                <i class="far fa-eye"></i> <?php echo _number($this->escape($firstStory['hits'])); ?>
                            </li>
                        <?php } ?>
                        <?php if ($block['showauthor']) { ?>
                            <?php foreach ($firstStory['authors'] as $author) { ?>
                                <li class="list-inline-item">
                                    <i class="fas fa-user"></i> <?php echo $author['authorRole']; ?> :
                                    <a title="<?php echo $author['authorName']; ?>"
                                       href="<?php echo $author['authorUrl']; ?>">
                                        <?php echo $author['authorName']; ?>
                                    </a>
                                </li>
                            <?php } ?>
                        <?php } ?>
                    </ul>
                <?php } ?>
                <?php if ($block['showdesc']) { ?>
                    <div class="widget-summary p-summary"><?php echo $firstStory['text_summary']; ?></div>
                <?php } ?>
                <?php if ($block['showmore']) { ?>
                    <div class="widget-story-more">
                        <a href="<?php echo $this->escape($firstStory['storyUrl']); ?>"
                           title="<?php echo $this->escape($firstStory['title']); ?>">
                            <?php echo _b('Read More'); ?>
                        </a>
                    </div>
                <?php } ?>
            </div>
            <meta itemprop="datePublished" content="<?php echo $this->escape(date("Y-m-d H:i:s", $firstStory['time_publish'])); ?>"/>
        </div>
    </div>
    <?php
    $block['showdesc'] = 0;
    $block['showmore'] = 0;
    $widgetSingleClass = '';
    include $this->template('story-vertical.phtml', 'widget', 'news'); ?>
</div>