<div class="widget-vertical clearfix">
    <?php foreach ($block['resources'] as $story) { ?>
        <?php $thumbUrl = Pi::api('doc', 'media')->getSingleLinkUrl($story['main_image'])->setConfigModule('news')->thumb('thumbnail'); ?>
        <div class="widget-vertical-single h-entry row <?php echo isset($widgetSingleClass) ? $widgetSingleClass : ''; ?>" itemscope
             itemtype="https://schema.org/Article">
            <?php if ($block['showimage'] && !empty($thumbUrl)) { ?>
                <div class="col-lg-4 col-md-3 storyImage">
                    <a itemprop="url mainEntityOfPage" title="<?php echo $this->escape($story['title']); ?>"
                       href="<?php echo $this->escape($story['storyUrl']); ?>">
                        <img itemprop="image" class="img-fluid u-photo"
                             src="<?php echo $thumbUrl; ?>"
                             alt="<?php echo $this->escape($story['title']); ?>"/>
                    </a>
                </div>
            <?php } ?>
            <div class="<?php if ($block['showimage'] && !empty($thumbUrl)) { ?>col-lg-8 col-md-9<?php } else { ?>col-lg-12 col-md-12<?php } ?> p-item h-card">
                <div class="widget-vertical-single-title p-name" itemprop="name headline">
                    <h3 class="clearfix">
                        <a itemprop="url mainEntityOfPage" href="<?php echo $this->escape($story['storyUrl']); ?>"
                           title="<?php echo $this->escape($story['title']); ?>">
                            <?php if ($story['important']) { ?> <span class="badge badge-danger"><?php echo _b('Important'); ?></span> <?php } ?>
                            <?php echo $this->escape($story['title']); ?>
                        </a>
                    </h3>
                </div>
                <div class="widget-vertical-single-information small">
                    <?php if ($block['showdate'] || $block['showhits'] || $block['showauthor']) { ?>
                        <ul class="text-muted list-inline">
                            <?php if ($block['showdate']) { ?>
                                <li class="list-inline-item dt-published">
                                    <i class="fas fa-calendar-alt"></i> <?php echo $this->escape($story['time_publish_view']); ?>
                                </li>
                            <?php } ?>
                            <?php if ($block['showhits']) { ?>
                                <li class="list-inline-item">
                                    <i class="far fa-eye"></i> <?php echo _number($this->escape($story['hits'])); ?>
                                </li>
                            <?php } ?>
                            <?php if ($block['showauthor']) { ?>
                                <?php foreach ($story['authors'] as $author) { ?>
                                    <li class="list-inline-item">
                                        <i class="fas fa-user"></i> <?php echo $author['authorRole']; ?> :
                                        <a title="<?php echo $author['authorName']; ?>"
                                           href="<?php echo $author['authorUrl']; ?>">
                                            <?php echo $author['authorName']; ?>
                                        </a>
                                    </li>
                                <?php } ?>
                            <?php } ?>
                        </ul>
                    <?php } ?>
                </div>
                <div class="clearfix">
                    <?php if ($block['showdesc']) { ?>
                        <div class="widget-summary p-summary"><?php echo $story['text_summary']; ?></div>
                    <?php } ?>
                    <?php if ($block['showmore']) { ?>
                        <div class="widget-story-more">
                            <a href="<?php echo $this->escape($story['storyUrl']); ?>"
                               title="<?php echo $this->escape($story['title']); ?>"><?php echo _b('Read More'); ?></a>
                        </div>
                    <?php } ?>
                </div>
            </div>
        </div>
        <meta itemprop="datePublished" content="<?php echo $this->escape(date("Y-m-d H:i:s", $story['time_publish'])); ?>"/>
        <meta itemprop="dateModified" content="<?php echo $this->escape(date("Y-m-d H:i:s", $story['time_update'])); ?>"/>
        <meta itemprop="author" content="<?php echo _escape(Pi::config('sitename')); ?>"/>
        <meta itemprop="publisher" content="<?php echo _escape(Pi::config('sitename')); ?>"/>
    <?php } ?>
</div>
