<div class="widget-verticalwide clearfix">
    <?php foreach ($block['resources'] as $story) { ?>
        <?php $mediumUrl = Pi::api('doc', 'media')->getSingleLinkUrl($story['main_image'])->setConfigModule('news')->thumb('medium'); ?>
        <div class="media h-entry clearfix" itemscope itemtype="https://schema.org/Article">
            <?php if ($block['showimage'] && !empty($mediumUrl)) { ?>
                <div class="clearfix">
                    <a itemprop="url" class="u-url"
                       href="<?php echo $this->escape($story['storyUrl']); ?>"
                       title="<?php echo $this->escape($story['title']); ?>">
                        <img itemprop="image" src="<?php echo $this->escape($mediumUrl); ?>"
                             alt="<?php echo $this->escape($story['title']); ?>"
                             class="media-object img-fluid u-photo"/>
                    </a>
                </div>
            <?php } ?>
            <div class="media-body p-item h-card">
                <h3 class="media-heading p-name itemSingleTitle" itemprop="name headline">
                    <a itemprop="url" href="<?php echo $this->escape($story['storyUrl']); ?>"
                       title="<?php echo $this->escape($story['title']); ?>">
                        <?php echo $this->escape($story['title']); ?>
                    </a>
                </h3>
                <div class="clearfix">
                    <?php if ($block['showdate'] || $block['showhits'] || $block['showauthor']) { ?>
                        <ul class="text-muted list-inline">
                            <?php if ($block['showdate']) { ?>
                                <li class="list-inline-item dt-published">
                                    <i class="fas fa-calendar-alt"></i> <?php echo $this->escape($story['time_publish_view']); ?>
                                </li>
                            <?php } ?>
                            <?php if ($block['showhits']) { ?>
                                <li class="list-inline-item">
                                    <i class="far fa-eye"></i> <?php echo _number($this->escape($story['hits'])); ?>
                                </li>
                            <?php } ?>
                            <?php if ($block['showauthor']) { ?>
                                <?php foreach ($story['authors'] as $author) { ?>
                                    <li class="list-inline-item">
                                        <i class="fas fa-user"></i> <?php echo $author['authorRole']; ?> :
                                        <a title="<?php echo $author['authorName']; ?>"
                                           href="<?php echo $author['authorUrl']; ?>">
                                            <?php echo $author['authorName']; ?>
                                        </a>
                                    </li>
                                <?php } ?>
                            <?php } ?>
                        </ul>
                    <?php } ?>
                    <?php if ($block['showdesc']) { ?>
                        <div class="widget-summary p-summary"><?php echo $story['text_summary']; ?></div>
                    <?php } ?>
                    <?php if ($block['showmore']) { ?>
                        <div class="widget-story-more">
                            <a href="<?php echo $this->escape($story['storyUrl']); ?>"
                               title="<?php echo $this->escape($story['title']); ?>"><?php echo _b('Read More'); ?></a>
                        </div>
                    <?php } ?>
                </div>
            </div>
            <meta itemprop="datePublished" content="<?php echo $this->escape(date("Y-m-d H:i:s", $story['time_publish'])); ?>"/>
        </div>
    <?php } ?>
</div>