<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <h3><?php echo $this->escape($title); ?></h3>
    <div class="row">
        <div class="col-md-5">
            <div class="card card-body bg-light mb-3">
                <div class="view-file">
                    <?php if ($file['type'] == 'video') { ?>

                    <?php } elseif ($file['type'] == 'audio') { ?>

                    <?php } elseif ($file['type'] == 'image') { ?>
                        <div class="attach-image text-center">
                            <img class="img-thumbnail"
                                 src="<?php echo $this->escape($file['view']); ?>"
                                 alt="<?php echo $this->escape($file['title']); ?>"/>
                        </div>
                    <?php } else { ?>
                        <div class="attach-image text-center">
                            <a class="btn btn-primary" rel="external"
                               title="<?php echo $this->escape($file['title']); ?>"
                               href="<?php echo $this->escape($file['downloadUrl']); ?>"><i
                                        class="fa fa-download-alt"></i> <?php _e('Get it'); ?></a>
                        </div>
                    <?php } ?>
                </div>
                <p><strong><?php _e('File title'); ?></strong> <?php echo $this->escape($file['title']); ?></p>
                <p><strong><?php _e('Item title'); ?></strong> <?php echo $this->escape($item['title']); ?></p>
            </div>
        </div>
        <div class="col-md-7"><?php echo $this->form($form); ?></div>
    </div>
    <p>
        <a class="btn btn-primary" title="<?php _e('Back'); ?>"
           href="<?php echo $this->url('', ['action' => 'index']); ?>"><i
                    class="fa fa-arrow-left"></i> <?php _e('Back'); ?></a>
    </p>
</div>