<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <h3><?php _e('List of attached files'); ?></h3>
    <?php if (!empty($files)) { ?>
        <table class="table table-striped table-bordered table-condensed">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('PerView'); ?></th>
                <th><?php _e('Information'); ?></th>
                <th><?php _e('Create'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($files as $file) { ?>
                <?php
                if ($file['status'] == 1) {
                    $labelClass = 'label-success';
                } else {
                    $labelClass = 'label-warning';
                }
                ?>
                <tr>
                    <td><span class="label <?php echo $labelClass; ?>"><?php echo $this->escape($file['id']); ?></span>
                    </td>
                    <td width="80">
                        <div class="preview-img"><img src="<?php echo $this->escape($file['preview']); ?>"
                                                      alt="<?php echo $this->escape($file['title']); ?>"/></div>
                    </td>
                    <td>
                        <p><strong><?php _e('Title'); ?></strong> <?php echo $this->escape($file['title']); ?></p>
                        <p><strong><?php _e('Item'); ?></strong> <?php echo $this->escape($file['itemTitle']); ?></p>
                    </td>
                    <td><?php echo $this->escape($file['time_create']); ?></td>
                    <td>
                        <a class="btn btn-primary" rel="external" title="<?php _e('Get'); ?>"
                           href="<?php echo $file['downloadUrl']; ?>"><i
                                class="fa fa-download-alt"></i> <?php _e('Get'); ?></a>
                        <a class="btn btn-primary" title="<?php _e('Edit'); ?>"
                           href="<?php echo $this->url('', array('action' => 'edit', 'id' => $file['id'])); ?>"><i
                                class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
                        <?php if ($file['item_table'] == 'story') { ?>
                            <a class="btn btn-primary" title="<?php _e('Edit from story'); ?>"
                               href="<?php echo $this->url('', array('action' => 'add', 'id' => $file['item_id'])); ?>"><i
                                    class="fa fa-edit"></i> <?php _e('Edit from story'); ?></a>
                        <?php } ?>
                    </td>
                </tr>
            <?php } ?>
        </table>
        <div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator'); ?></div>
        <p>
            <span class="label label-success"><?php _e('Published'); ?></span>
            <span class="label label-warning"><?php _e('Pending review'); ?></span>
        </p>
    <?php } else { ?>
        <div class="alert alert-danger">
            <h4><?php _e('Error'); ?></h4>

            <p><?php _e('No file upload yet'); ?></p>
        </div>
    <?php } ?>
</div>