<?php
$this->css($this->assetModule('css/admin.css'));
$this->css($this->assetModule('script/system-ui.css', 'system'));
$this->jQuery('ui/jquery-ui.min.js');
?>
<div class="clearfix" id="tree-template">
    <p>
        <a class="btn btn-primary" title="<?php _e('Add attribute'); ?>" href="<?php echo $this->url('', array('action' => 'update')); ?>"><i class="fa fa-random"></i> <?php _e('Add attribute'); ?></a>
    </p>
    <h3><?php _e('List of attributes'); ?></h3>
    <div id="attribute-sort">
        <div class="attribute-field">
            <?php foreach($positions as $key => $position) { ?>
                <?php if (isset($fields[$key]) && !empty($fields[$key])) { ?>
                    <h4><?php echo $this->escape($position); ?></h4>
                    <?php foreach($fields[$key] as $field) { ?>
                        <div id="mod_<?php echo $this->escape($field['id']); ?>">
                            <div class="tree-item">
                                <div class="tree-item-header" style="cursor:move;">
                                    <div class="col-md-4">
                                        <strong><?php _e('Title'); ?></strong> : <span> <?php echo $this->escape($field['title']); ?> </span>
                                    </div>
                                    <div class="col-md-2">
                                        <strong><?php _e('Type'); ?></strong> : <span> <?php echo $this->escape($field['type']); ?> </span>
                                    </div>
                                    <div class="col-md-3">
                                        <strong><?php _e('Set'); ?></strong> : <span> <?php echo $this->escape($field['position_view']); ?> </span>
                                    </div>
                                    <div class="col-md-2">
                                        <a class="btn btn-link" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', array('action' => 'update', 'id' => $field['id'])); ?>"><i class="fa fa-edit"></i></a>
                                        <a class="btn btn-link" title="<?php _e('Delete'); ?>" href="<?php echo $this->url('', array('action' => 'delete', 'id' => $field['id'])); ?>"><i class="fa fa-trash-o"></i></a>
                                        <span class="label <?php if($field['status']) { echo'label-success'; } else { echo 'label-danger';} ?>"><i class="fa fa-exclamation-circle"></i></span>
                                        <span class="label <?php if($field['search']) { echo'label-success'; } else { echo 'label-danger';} ?>"><i class="fa fa-search"></i></span>
                                    </div>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                <?php } ?>
            <?php } ?>
        </div>
    </div>
</div>
<script type="text/javascript" >
    $(document).ready(function() {
        $('#attribute-sort .attribute-field').sortable({
            update: function(event, ui) {
                var list = $(this).sortable('serialize');
                $.post("<?php echo $this->url('', array('action' => 'sort')); ?>", list);
            }
        });
    });
</script>