<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <div class="admin-header clearfix">
        <div class="col-md-7">
            <a class="btn btn-primary" title="<?php _e('Add Author'); ?>"
               href="<?php echo $this->url('', ['controller' => 'author', 'action' => 'update']); ?>"><i
                        class="fas fa-plus"></i> <?php _e('Add Author'); ?></a>
        </div>
        <div class="col-md-5">
            <?php echo $this->form($form, 'inline'); ?>
        </div>
    </div>
    <?php if (!empty($authors)) { ?>
        <h3><?php _e('List of authors'); ?></h3>
        <table class="table table-striped table-bordered table-sm">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Title'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($authors as $author) { ?>
                <?php
                if ($author['status'] == 1) {
                    $labelIdClass = 'badge badge-success';
                } else {
                    $labelIdClass = 'badge badge-warning';
                }
                ?>
                <tr>
                    <td><span
                                class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($author['id']); ?></span>
                    </td>
                    <td><?php echo $this->escape($author['title']); ?></td>
                    <td>
                        <a class="btn btn-primary" title="<?php _e('View'); ?>"
                           href="<?php echo $this->url(
                               'news', ['module' => $module, 'controller' => 'author', 'slug' => $this->escape($author['slug'])]
                           ); ?>"><i
                                    class="far fa-eye"></i> <?php _e('View'); ?></a>
                        <a class="btn btn-primary" title="<?php _e('Edit'); ?>"
                           href="<?php echo $this->url('', ['action' => 'update', 'id' => $author['id']]); ?>"><i
                                    class="fas fa-edit"></i> <?php _e('Edit'); ?></a>
                    </td>
                </tr>
            <?php } ?>
        </table>
        <div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?></div>
        <p>
            <span class="badge badge-success"><?php _e('Published'); ?></span>
            <span class="badge badge-warning"><?php _e('Pending review'); ?></span>
            <span class="badge badge-danger"><?php _e('Trash'); ?></span>
        </p>
    <?php } ?>
</div>