<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="news">
	<div class="admin-header clearfix well well-sm">
		<div class="col-md-7">
			<a class="btn btn-success" title="<?php _e('Author list'); ?>" href="<?php echo $this->url('', array('controller' => 'author', 'action' => 'index')); ?>"><i class="fa fa-folder-open"></i> <?php _e('Author list'); ?></a>
			<a class="btn btn-primary" title="<?php _e('Add Author'); ?>" href="<?php echo $this->url('', array('controller' => 'author', 'action' => 'update')); ?>"><i class="fa fa-folder-open"></i> <?php _e('Add Author'); ?></a>
			<a class="btn btn-primary" title="<?php _e('Role list'); ?>" href="<?php echo $this->url('', array('controller' => 'author', 'action' => 'role')); ?>"><i class="fa fa-folder-open"></i> <?php _e('Role list'); ?></a>
			<a class="btn btn-primary" title="<?php _e('Add Role'); ?>" href="<?php echo $this->url('', array('controller' => 'author', 'action' => 'roleUpdate')); ?>"><i class="fa fa-folder-open"></i> <?php _e('Add Role'); ?></a>
		</div>
		<div class="col-md-5">
			<div class="form-inline"><?php include $this->templateComponent('forms'); ?></div>
		</div>
	</div>
	<h3><?php _e('List of authors'); ?></h3>
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<th><?php _e('ID'); ?></th>
			<th><?php _e('Title'); ?></th>
			<th><?php _e('Action'); ?></th>
		</tr>
		<?php foreach($authors as $author) { ?>
		<?php
		if($author['status'] == 1) {
			$labelIdClass = 'label label-success';	
		} else {
			$labelIdClass = 'label label-warning';	
		}	
		?>
		<tr>
			<td><span class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($author['id']); ?></span></td>
			<td><?php echo $this->escape($author['title']); ?></td>
			<td>
				<a class="btn btn-primary" title="<?php _e('View'); ?>" href="<?php echo $this->url('news',  array('module' => $module, 'controller' => 'author', 'slug' => $this->escape($author['slug']))); ?>"><i class="fa fa-eye"></i> <?php _e('View'); ?></a>
				<a class="btn btn-primary" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', array('action' => 'update', 'id' => $author['id'])); ?>"><i class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
			</td>
		</tr>
		<?php } ?>
	</table>
	<div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?></div>
	<p>
		<span class="label label-success"><?php _e('Published'); ?></span>
		<span class="label label-warning"><?php _e('Pending review'); ?></span>
		<span class="label label-danger"><?php _e('Trash'); ?></span>
	</p>
</div>