<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <p><a class="btn btn-primary" title="<?php _e('Add Role'); ?>"
          href="<?php echo $this->url('', ['action' => 'update']); ?>"><i
                    class="fa fa-plus"></i> <?php _e('Add Role'); ?></a></p>
    <?php if (!empty($roles)) { ?>
        <h3><?php _e('List of roles'); ?></h3>
        <table class="table table-striped table-bordered table-sm">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Title'); ?></th>
                <th><?php _e('Action'); ?></th>
            </tr>
            <?php foreach ($roles as $role) { ?>
                <?php
                if ($role['status'] == 1) {
                    $labelIdClass = 'badge badge-success';
                } else {
                    $labelIdClass = 'badge badge-warning';
                }
                ?>
                <tr>
                    <td><span
                                class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($role['id']); ?></span>
                    </td>
                    <td><?php echo $this->escape($role['title']); ?></td>
                    <td>
                        <a class="btn btn-primary" title="<?php _e('Edit'); ?>"
                           href="<?php echo $this->url('', ['action' => 'update', 'id' => $role['id']]); ?>"><i
                                    class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
                    </td>
                </tr>
            <?php } ?>
        </table>
        <p>
            <span class="badge badge-success"><?php _e('Published'); ?></span>
            <span class="badge badge-warning"><?php _e('Pending review'); ?></span>
            <span class="badge badge-danger"><?php _e('Trash'); ?></span>
        </p>
    <?php } ?>
</div>