<?php
    $this->css(array(
        $this->assetModule('css/admin.css'),
        $this->assetModule('script/system-ui.css', 'system'),
    ));
    $this->jQuery();
    $this->js(array(
        $this->assetModule('script/cache.js', 'system'),
        $this->assetModule('script/tip-alert.js', 'system'),
    ));
?>
<div class="news">
	<div class="btn-group">
	   <a class="btn" title="<?php _e('Back'); ?>" href="<?php echo $this->url('', array('action' => 'index')); ?>"><i class="icon-arrow-left"></i> <?php _e('Back'); ?></a>
	   <a class="btn" title="<?php _e('Add Story'); ?>" href="<?php echo $this->url('', array('controller' => 'story', 'action' => 'update')); ?>"><i class="icon-file"></i> <?php _e('Add Story'); ?></a>
	   <a class="btn" title="<?php _e('Add Topic'); ?>" href="<?php echo $this->url('', array('controller' => 'topic', 'action' => 'update')); ?>"><i class="icon-folder-open"></i> <?php _e('Add Topic'); ?></a>
	   <a class="btn" title="<?php _e('Add Moderator'); ?>" href="<?php echo $this->url('', array('controller' => 'moderator', 'action' => 'update')); ?>"><i class="icon-user"></i> <?php _e('Add Moderator'); ?></a>
	   <a class="btn" title="<?php _e('Add Spotlight'); ?>" href="<?php echo $this->url('', array('controller' => 'spotlight', 'action' => 'update')); ?>"><i class="icon-user"></i> <?php _e('Add Spotlight'); ?></a>
	   <a class="btn" title="<?php _e('Add Extra'); ?>" href="<?php echo $this->url('', array('controller' => 'spotlight', 'action' => 'update')); ?>"><i class="icon-random"></i> <?php _e('Add Extra'); ?></a>
	</div>
	<div class="row">
		<div class="span3">
			<h5><?php _e('Levels'); ?></h5>
			<div class="sub-nav">
				<ul class="nav nav-tabs nav-stacked">
					<li><a title="<?php _e('1- Story'); ?>" href=""><?php _e('1- Story'); ?></a></li>
					<li><a title="<?php _e('2- Attach'); ?>" href=""><?php _e('2- Attach'); ?></a></li>
					<li class="active"><a title="<?php _e('3- Extra'); ?>"><?php _e('3- Extra'); ?></a></li>
				</ul>
			</div>
		</div>
		<div class="span9">
			<h2><?php //echo $this->escape($title); ?></h2>
			<div id="extra-form">
			<?php //include $this->templateComponent('form'); ?>
			</div>
		</div>
	</div>
</div>