<?php
    $this->css(array(
        $this->assetModule('css/admin.css'),
        $this->assetModule('script/system-ui.css', 'system'),
    ));
    $this->jQuery();
    $this->js($this->assetModule('script/system-msg.js', 'system'));
?>
<div class="news">
	<div class="btn-group">
	   <a class="btn" title="<?php _e('Back'); ?>" href="<?php echo $this->url('', array('action' => 'index')); ?>"><i class="icon-arrow-left"></i> <?php _e('Back'); ?></a>
	   <a class="btn" title="<?php _e('Add Story'); ?>" href="<?php echo $this->url('', array('controller' => 'story', 'action' => 'update')); ?>"><i class="icon-file"></i> <?php _e('Add Story'); ?></a>
	   <a class="btn" title="<?php _e('Add Topic'); ?>" href="<?php echo $this->url('', array('controller' => 'topic', 'action' => 'update')); ?>"><i class="icon-folder-open"></i> <?php _e('Add Topic'); ?></a>
	   <a class="btn" title="<?php _e('Add Moderator'); ?>" href="<?php echo $this->url('', array('controller' => 'moderator', 'action' => 'update')); ?>"><i class="icon-user"></i> <?php _e('Add Moderator'); ?></a>
	   <a class="btn" title="<?php _e('Add Spotlight'); ?>" href="<?php echo $this->url('', array('controller' => 'spotlight', 'action' => 'update')); ?>"><i class="icon-user"></i> <?php _e('Add Spotlight'); ?></a>
	   <a class="btn" title="<?php _e('Add Extra'); ?>" href="<?php echo $this->url('', array('controller' => 'extra', 'action' => 'update')); ?>"><i class="icon-random"></i> <?php _e('Add Extra'); ?></a>
	</div>
	<br />
	<h2><?php echo $this->escape($title); ?></h2>
	<div id="extra-form"><?php include $this->templateComponent('form'); ?></div>
</div>
<script type="text/javascript" >
(function($){
    $("#extra-form").on("click","button",function(){
       systemMessage.wait("<?php _e('Remove image extra in process'); ?>");
       $.getJSON($(this).attr("data-link")).done(function(result){
          if(result.status==1){
             systemMessage.succ(result.message);
          }else{
             systemMessage.fail(result.message);
          }
       });
    });
})(jQuery)
</script>