<?php 
	$this->css($this->assetModule('css/admin.css'));
	$this->css($this->assetModule('script/system-ui.css', 'system')); 
	$this->jQuery('ui/jquery-ui.custom.min.js');
?>
<div class="news" id="tree-template"> 
	<?php $navExtra = 1; ?>
	<?php include $this->template('admin/product_nav'); ?>
    <p>
	   <a class="btn btn-primary" title="<?php _e('Add Extra'); ?>" href="<?php echo $this->url('', array('action' => 'update')); ?>"><i class="fa fa-random"></i> <?php _e('Add Extra'); ?></a>
	</p>
	<h3><?php _e('List of extra fields'); ?></h3>
	<div id="extra-sort">
		<div class="extra-field">
			<?php foreach($fields as $field) { ?>
			<div id="mod_<?php echo $this->escape($field['id']); ?>">
				<div class="tree-item">
					<div class="tree-item-header" style="cursor:move;">
						<div class="pad2">
	                        <?php if($field['image']) { ?>
	                        <div class="pull-left col-md-1">
	                            <img height="20" width="20" src="<?php echo $this->escape($field['imageUrl']); ?>" alt="<?php echo $this->escape($field['title']); ?>" />
	                        </div>
	                        <?php } ?>
						    <div class="pull-left <?php if($field['image']) { ?>col-md-3<?php } else { ?>col-md-4<?php } ?>"><strong><?php _e('Title'); ?></strong> <?php echo $this->escape($field['title']); ?></div>
						    <div class="pull-left col-md-2"><strong><?php _e('Type'); ?></strong> <?php echo $this->escape($field['type']); ?></div>
						    <div class="pull-right btn-group col-md-2">
								<a class="btn btn-link" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', array('action' => 'update', 'id' => $field['id'])); ?>"><i class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
								<a class="btn btn-link" title="<?php _e('Delete'); ?>" href="<?php echo $this->url('', array('action' => 'delete', 'id' => $field['id'])); ?>"><i class="fa fa-trash"></i> <?php _e('Delete'); ?></a>
							</div>
							<div class="pull-right col-md-1"><span class="label <?php if($field['status']) { echo'label-success'; } else { echo 'label-danger';} ?>"><?php _e('Status'); ?></span></div>
							<div class="pull-right col-md-1"><span class="label <?php if($field['search']) { echo'label-success'; } else { echo 'label-danger';} ?>"><?php _e('Search'); ?></span></div>
						</div>
					</div>
				</div>
			</div>
			<?php } ?>
		</div>
	</div>
</div>
<script type="text/javascript" >
$(document).ready(function() {
	$('#extra-sort .extra-field').sortable({
    	update: function(event, ui) {
        	var list = $(this).sortable('serialize');
        	$.post("<?php echo $this->url('', array('action' => 'extraSort')); ?>", list);
    	}
	});
});
</script>