<?php
    $this->css(array(
        $this->assetModule('css/admin.css'),
        $this->assetModule('script/system-ui.css', 'system'),
    ));
    $this->jQuery();
    $this->js(array(
        $this->assetModule('script/cache.js', 'system'),
        $this->assetModule('script/tip-alert.js', 'system'),
    ));
?>
<div class="news">
	<p>
	   <a class="btn btn-primary" title="<?php _e('Back'); ?>" href="<?php echo $this->url('', array('action' => 'index')); ?>"><i class="fa fa-arrow-left"></i> <?php _e('Back'); ?></a>
	   <a class="btn btn-primary" title="<?php _e('Add Extra'); ?>" href="<?php echo $this->url('', array('controller' => 'spotlight', 'action' => 'update')); ?>"><i class="fa fa-random"></i> <?php _e('Add Extra'); ?></a>
	</p>
	<div class="row">
		<div class="col-md-3">
			<h5><?php _e('Levels'); ?></h5>
			<div class="sub-nav">
				<ul class="nav nav-tabs nav-stacked">
					<li><a title="<?php _e('1- Story'); ?>" href=""><?php _e('1- Story'); ?></a></li>
					<li><a title="<?php _e('2- Attach'); ?>" href=""><?php _e('2- Attach'); ?></a></li>
					<li class="active"><a title="<?php _e('3- Extra'); ?>"><?php _e('3- Extra'); ?></a></li>
				</ul>
			</div>
		</div>
		<div class="col-md-9">
			<h2><?php //echo $this->escape($title); ?></h2>
			<div id="extra-form">
			<?php //include $this->templateComponent('forms'); ?>
			</div>
		</div>
	</div>
</div>