<?php $this->css($this->assetModule('css/admin.css')); ?>
<?php if ($config['microblog_active']) { ?>
    <div class="clearfix">
        <p>
            <a class="btn btn-primary" title="<?php _e('New news'); ?>"
               href="<?php echo $this->url('', array('controller' => 'microblog', 'action' => 'update', 'type' => 'news')); ?>"><i
                    class="fa fa-folder-open"></i><?php _e('New news'); ?></a>
            <a class="btn btn-primary" title="<?php _e('New post'); ?>"
               href="<?php echo $this->url('', array('controller' => 'microblog', 'action' => 'update', 'type' => 'post')); ?>"><i
                    class="fa fa-folder-open"></i><?php _e('New post'); ?></a>
        </p>

        <h3><?php _e('List of posts'); ?></h3>
        <table class="table table-striped table-bordered table-condensed">
            <tr>
                <th><?php _e('ID'); ?></th>
                <th><?php _e('Text'); ?></th>
            </tr>
            <?php foreach ($list as $microblog) { ?>
                <?php
                if ($microblog['status'] == 1) {
                    $labelIdClass = 'label-success';
                } elseif ($microblog['status'] == 5) {
                    $labelIdClass = 'label label-danger';
                } else {
                    $labelIdClass = 'label-warning';
                }
                ?>
                <tr>
                    <td><span
                            class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($microblog['id']); ?></span>
                    </td>
                    <td>
                        <p><?php echo $this->escape($microblog['post']); ?></p>

                        <p>
                            <?php if (!empty($microblog['microblogUrl'])) { ?>
                                <a class="btn btn-primary btn-xs" title="<?php _e('View'); ?>"
                                   href="<?php echo $this->escape($microblog['microblogUrl']); ?>"><i
                                        class="fa fa-eye"></i> <?php _e('View'); ?></a>
                            <?php } ?>
                            <a class="btn btn-primary btn-xs" title="<?php _e('Edit'); ?>"
                               href="<?php echo $this->url('', array('action' => 'update', 'id' => $microblog['id'])); ?>"><i
                                    class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
                            <a class="btn btn-danger btn-xs" title="<?php _e('Delete'); ?>"
                               href="<?php echo $this->url('', array('action' => 'delete', 'id' => $microblog['id'])); ?>"
                               onclick="return confirm('<?php echo _a('Are you sure to delete this story?'); ?>')"><i
                                    class="fa fa-trash"></i> <?php _e('Delete'); ?></a>
                            <strong><?php _e('Published'); ?></strong>
                            : <?php echo $this->escape($microblog['time_publish']); ?>
                            <strong><?php _e('By'); ?></strong>
                            : <?php echo $this->escape($microblog['user']['name']); ?>
                            ( <?php echo $this->escape($microblog['user']['identity']); ?> )
                        </p>
                    </td>
                </tr>
            <?php } ?>
        </table>
        <div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?></div>
        <p>
            <span class="label label-success"><?php _e('Published'); ?></span>
            <span class="label label-warning"><?php _e('Pending review'); ?></span>
            <span class="label label-danger"><?php _e('Trash'); ?></span>
        </p>
    </div>
<?php } else { ?>
    <div class="alert alert-danger" role="alert">
        <?php _e('Microblog system is inactive, if you want use it , please active it from module config'); ?>
    </div>
<?php } ?>