<?php
    $this->css($this->assetModule('script/system-ui.css'));
    $this->jQuery();
    $this->Backbone();
    $this->js($this->assetModule('script/system-msg.js', 'system'));
?>
<ul class="nav nav-tabs">
    <li class="<?php if ($name == 'read') { echo 'active'; } ?>">
        <a href="<?php echo $this->url('', array('controller' => 'permission', 'action' => 'index', 'section' => $section, 'name' => 'read')); ?>"><?php _e('Read'); ?></a>
    </li>
    <li class="<?php if ($name == 'write') { echo 'active'; } ?>">
        <a href="<?php echo $this->url('', array('controller' => 'permission', 'action' => 'index', 'section' => $section, 'name' => 'write')); ?>"><?php _e('Write'); ?></a>
    </li>
    <li class="<?php if ($name == 'manage') { echo 'active'; } ?>">
        <a href="<?php echo $this->url('', array('controller' => 'permission', 'action' => 'index', 'section' => $section, 'name' => 'manage')); ?>"><?php _e('Manage'); ?></a>
    </li>
    <li class="<?php if ($name == 'approve') { echo 'active'; } ?>">
        <a href="<?php echo $this->url('', array('controller' => 'permission', 'action' => 'index', 'section' => $section, 'name' => 'approve')); ?>"><?php _e('Approve'); ?></a>        
    </li>
</ul>


<div class="page-perm row-fluid">
    <div class="span2 well well-small">
        <ul class="nav nav-list">
            <?php foreach ($roles as $key => $value) { ?>
            <li <?php if ($key == $role) { echo 'class="active"'; } ?>>
                <a href="<?php echo $this->url('', array('controller' => 'permission', 'action' => 'index', 'section' => $section, 'role' => $key, 'name' => $name)); ?>"><?php echo $value; ?></a>
            </li>
            <?php } ?>
        </ul>
    </div>
    <div class="span10">
       
    </div>
</div>