<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="news">
	<div class="btn-group">
	   <a class="btn" title="<?php _e('Add Story'); ?>" href="<?php echo $this->url('', array('controller' => 'story', 'action' => 'update')); ?>"><i class="icon-file"></i> <?php _e('Add Story'); ?></a>
	   <a class="btn" title="<?php _e('Add Topic'); ?>" href="<?php echo $this->url('', array('controller' => 'topic', 'action' => 'update')); ?>"><i class="icon-folder-open"></i> <?php _e('Add Topic'); ?></a>
	   <a class="btn" title="<?php _e('Add Moderator'); ?>" href="<?php echo $this->url('', array('controller' => 'moderator', 'action' => 'update')); ?>"><i class="icon-user"></i> <?php _e('Add Moderator'); ?></a>
	   <a class="btn" title="<?php _e('Add Spotlight'); ?>" href="<?php echo $this->url('', array('controller' => 'spotlight', 'action' => 'update')); ?>"><i class="icon-user"></i> <?php _e('Add Spotlight'); ?></a>
	   <a class="btn" title="<?php _e('Add Extra'); ?>" href="<?php echo $this->url('', array('controller' => 'extra', 'action' => 'update')); ?>"><i class="icon-random"></i> <?php _e('Add Extra'); ?></a>
	</div>
	<h3><?php _e('List of spotlights'); ?></h3>
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<th><?php _e('ID'); ?></th>
			<th><?php _e('Story'); ?></th>
			<th><?php _e('Show in'); ?></th>
			<th><?php _e('Publish'); ?></th>
			<th><?php _e('Expire'); ?></th>
			<th><?php _e('Action'); ?></th>
		</tr>
		<?php foreach($spotlights as $spotlight) { ?>
		<tr>
			<td><?php echo $this->escape($spotlight['id']); ?></td>
			<td><?php echo $this->escape($spotlight['storytitle']); ?></a></td>
			<td><?php echo $this->escape($spotlight['topictitle']); ?></td>
			<td><?php echo $this->escape($spotlight['publish']); ?></td>
			<td><?php echo $this->escape($spotlight['expire']); ?></td>
			<td>
				<div class="btn-group">
				   <a class="btn" title="<?php _e('Veiw story'); ?>" href="<?php echo $this->url('.news', array('module' => $module, 'controller' => 'story', 'alias' => $this->escape($spotlight['storyalias']))); ?>"><i class="icon-edit"></i> <?php _e('Veiw story'); ?></a>
					<a class="btn" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', array('action' => 'update', 'id' => $spotlight['id'])); ?>"><i class="icon-edit"></i> <?php _e('Edit'); ?></a>
					<a class="btn" title="<?php _e('Delete'); ?>" href="<?php echo $this->url('', array('action' => 'delete', 'id' => $spotlight['id'])); ?>"><i class="icon-trash"></i> <?php _e('Delete'); ?></a>
				</div>
			</td>
		</tr>
		<?php } ?>
	</table>
	<div class="paginator"><?php echo $this->paginationControl($spotlights, 'Sliding', 'paginator'); ?></div>
</div>