<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="news">
	<p>
	   <a class="btn btn-primary" title="<?php _e('Add Spotlight'); ?>" href="<?php echo $this->url('', array('controller' => 'spotlight', 'action' => 'update')); ?>"><i class="fa fa-user"></i> <?php _e('Add Spotlight'); ?></a>
	</p>
	<h3><?php _e('List of spotlights'); ?></h3>
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<th><?php _e('ID'); ?></th>
			<th><?php _e('Story'); ?></th>
			<th><?php _e('Show in'); ?></th>
			<th><?php _e('Publish date'); ?></th>
			<th><?php _e('Expire date'); ?></th>
			<th><?php _e('Action'); ?></th>
		</tr>
		<?php foreach($spotlightList as $spotlight) { ?>
		<tr>
			<td><?php echo $this->escape($spotlight['id']); ?></td>
			<td><?php echo $this->escape($spotlight['storytitle']); ?></a></td>
			<td><?php echo $this->escape($spotlight['topictitle']); ?></td>
			<td><?php echo $this->escape($spotlight['time_publish']); ?></td>
			<td><?php echo $this->escape($spotlight['time_expire']); ?></td>
			<td>
				<a class="btn btn-primary" title="<?php _e('Veiw story'); ?>" href="<?php echo $this->url('news', array('module' => $module, 'controller' => 'story', 'slug' => $this->escape($spotlight['storyslug']))); ?>"><i class="fa fa-edit"></i> <?php _e('Veiw story'); ?></a>
				<a class="btn btn-primary" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', array('action' => 'update', 'id' => $spotlight['id'])); ?>"><i class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
				<a class="btn btn-danger" title="<?php _e('Delete'); ?>" href="<?php echo $this->url('', array('action' => 'delete', 'id' => $spotlight['id'])); ?>"><i class="fa fa-trash-o"></i> <?php _e('Delete'); ?></a>
			</td>
		</tr>
		<?php } ?>
	</table>
	<div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?></div>
</div>