<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <p>
        <a class="btn btn-primary" title="<?php _e('Back'); ?>"
           href="<?php echo $this->url('', array('action' => 'index')); ?>"><i
                class="fa fa-arrow-left"></i> <?php _e('Back'); ?></a>
    </p>

    <h3><?php echo $this->escape($title); ?></h3>
    <?php echo $this->form($form); ?>
</div>