<?php
/* $this->css(
    [
        $this->assetModule('css/admin.css'),
        $this->assetModule('script/system-ui.css', 'system'),
    ]
);
$this->jQuery();
$this->js($this->assetModule('script/system-msg.js', 'system')); */
$this->css($this->assetModule('css/admin.css'));
?>
<div class="clearfix">
    <div class="admin-header clearfix row">
        <div class="col-md-12">
            <div class="card-group" id="accordion" role="tablist" aria-multiselectable="true">
                <div class="card card-body bg-light mb-3">
                    <div class="card-heading" role="tab" id="headingHelp">
                        <h4 class="card-title">
                            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseHelp" aria-expanded="false"
                               aria-controls="collapseHelp">
                                <i class="fas fa-plus"></i> <?php _e('Description about add new story'); ?>
                            </a>
                        </h4>
                    </div>
                    <div id="collapseHelp" class="card-collapse collapse" role="tabpanel">
                        <div class="card-text">
                            <p><?php _e(
                                    'You can select many types on submit new story, each type have different template and view and useful for special usage'
                                ); ?></p>
                            <dl class="dl-horizontal">
                                <dt><strong class="text-danger"><?php _e('Text'); ?></strong></dt>
                                <dd><?php _e(
                                        'Text type, default view format main image set on center and under title and extra images and information set on sidebar'
                                    ); ?></dd>
                            </dl>
                            <dl class="dl-horizontal">
                                <dt><strong class="text-danger"><?php _e('Article'); ?></strong></dt>
                                <dd><?php _e('Article view, main image and extra information set on sidebar and text set on center and under title'); ?></dd>
                            </dl>
                            <dl class="dl-horizontal">
                                <dt><strong class="text-danger"><?php _e('Magazine'); ?></strong></dt>
                                <dd><?php _e(
                                        'Magazine view, main and extra images set on center and text under them , after that extra information , without sidebar'
                                    ); ?></dd>
                            </dl>
                            <dl class="dl-horizontal">
                                <dt><strong class="text-danger"><?php _e('Blog post'); ?></strong></dt>
                                <dd><?php _e('You need install blog module and story show on blog system, for better SEO'); ?></dd>
                            </dl>
                            <dl class="dl-horizontal">
                                <dt><strong class="text-danger"><?php _e('Image'); ?></strong></dt>
                                <dd><?php _e(
                                        'Single image set on center and under title, other texts , extra information and images set under main and big image, you can use topic as gallery album and each story is single image on album'
                                    ); ?></dd>
                            </dl>
                            <dl class="dl-horizontal">
                                <dt><strong class="text-danger"><?php _e('Gallery'); ?></strong></dt>
                                <dd><?php _e(
                                        'Gallery album view, main image and other extra images set as album on same position, all other texts and extra information set under images, you can use topic as category for albums and each story is single album by images'
                                    ); ?></dd>
                            </dl>
                            <dl class="dl-horizontal">
                                <dt><strong class="text-danger"><?php _e('Media'); ?></strong></dt>
                                <dd><?php _e(
                                        'Media type load video or audio player under title and set all extra information on side bar and texts under player, you need attach mp4 or mp3 files to story or make audio / video attribute and put your media file link'
                                    ); ?></dd>
                            </dl>
                            <dl class="dl-horizontal">
                                <dt><strong class="text-danger"><?php _e('Download'); ?></strong></dt>
                                <dd><?php _e(
                                        'Download template and show download button for get file by user, you need attach file to story or make file attribute and put your file link'
                                    ); ?></dd>
                            </dl>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-7">
            <div class="nav">
                <div class="btn-group">
                    <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
                        <i class="fas fa-plus"></i> <?php _e('Add new story'); ?>
                    </button>
                    <div class="dropdown-menu" role="menu">
                        <?php if (!$config['admin_deactivate_view']) { ?>
                            <a class="dropdown-item" title="<?php _e('Add new text'); ?>"
                                   href="<?php echo $this->url('', ['controller' => 'story', 'action' => 'add', 'type' => 'text']); ?>"><i
                                            class="fas fa-sticky-note"></i> <?php _e('Add new text'); ?></a>
                            <a class="dropdown-item" title="<?php _e('Add new article'); ?>"
                                   href="<?php echo $this->url('', ['controller' => 'story', 'action' => 'add', 'type' => 'article']); ?>"><i
                                            class="fas fa-folder"></i> <?php _e('Add new article'); ?></a>
                            <a class="dropdown-item" title="<?php _e('Add new magazine'); ?>"
                                   href="<?php echo $this->url('', ['controller' => 'story', 'action' => 'add', 'type' => 'magazine']); ?>"><i
                                            class="fas fa-chart-pie"></i> <?php _e('Add new magazine'); ?></a>
                            <a class="dropdown-item" title="<?php _e('Add new gallery album'); ?>"
                                   href="<?php echo $this->url('', ['controller' => 'story', 'action' => 'add', 'type' => 'gallery']); ?>"><i
                                            class="fas fa-camera"></i> <?php _e('Add new gallery album'); ?></a>
                            <a class="dropdown-item" title="<?php _e('Add new single image'); ?>"
                                   href="<?php echo $this->url('', ['controller' => 'story', 'action' => 'add', 'type' => 'image']); ?>"><i
                                            class="far fa-picture"></i> <?php _e('Add new single image'); ?></a>
                           <a class="dropdown-item" title="<?php _e('Add new media'); ?>"
                                   href="<?php echo $this->url('', ['controller' => 'story', 'action' => 'add', 'type' => 'media']); ?>"><i
                                            class="fas fa-video"></i> <?php _e('Add new media'); ?></a>
                            <a class="dropdown-item" title="<?php _e('Add new download'); ?>"
                                   href="<?php echo $this->url('', ['controller' => 'story', 'action' => 'add', 'type' => 'download']); ?>"><i
                                            class="fas fa-download"></i> <?php _e('Add new download'); ?></a>
                        <?php } ?>
                        <?php if (Pi::service('module')->isActive('blog')) { ?>
                            <a class="dropdown-item" title="<?php _e('Add new blog post'); ?>"
                                   href="<?php echo $this->url('', ['controller' => 'story', 'action' => 'add', 'type' => 'post']); ?>"><i
                                            class="fas fa-globe-americas"></i> <?php _e('Add new blog post'); ?></a>
                        <?php } ?>
                        <?php if (!Pi::service('module')->isActive('blog') && $config['admin_deactivate_view']) { ?>
                            <?php _e('News module front page is deactivate'); ?>
                        <?php } ?>
                    </div>
                </div>
                <div class="btn-group">
                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                        <i class="far fa-eye"></i> <?php _e('View'); ?>
                    </button>
                    <div class="dropdown-menu" role="menu">
                        <a class="dropdown-item" title="<?php _e('All stories'); ?>"
                               href="<?php echo $this->url('', ['controller' => 'story', 'action' => 'index']); ?>"><i
                                        class="fas fa-file"></i> <?php _e('All stories'); ?></a>
                        <a class="dropdown-item" title="<?php _e('Published'); ?>"
                               href="<?php echo $this->url('', ['controller' => 'story', 'action' => 'index', 'status' => '1']); ?>"><i
                                        class="fas fa-file"></i> <?php _e('Published'); ?></a>
                        <a class="dropdown-item" title="<?php _e('Pending review'); ?>"
                               href="<?php echo $this->url('', ['controller' => 'story', 'action' => 'index', 'status' => '2']); ?>"><i
                                        class="fas fa-file"></i> <?php _e('Pending review'); ?></a>
                        <a class="dropdown-item" title="<?php _e('Draft'); ?>"
                               href="<?php echo $this->url('', ['controller' => 'story', 'action' => 'index', 'status' => '3']); ?>"><i
                                        class="fas fa-file"></i> <?php _e('Draft'); ?></a>
                        <a class="dropdown-item" title="<?php _e('Private'); ?>"
                               href="<?php echo $this->url('', ['controller' => 'story', 'action' => 'index', 'status' => '4']); ?>"><i
                                        class="fas fa-file"></i> <?php _e('Private'); ?></a>
                        <a class="dropdown-item" title="<?php _e('Trash'); ?>"
                               href="<?php echo $this->url('', ['controller' => 'story', 'action' => 'index', 'status' => '5']); ?>"><i
                                        class="fas fa-trash-alt"></i> <?php _e('Trash'); ?></a>
                        <a class="dropdown-item" title="<?php _e('System draft'); ?>"
                               href="<?php echo $this->url('', ['controller' => 'story', 'action' => 'index', 'status' => '6']); ?>"><i
                                        class="fas fa-pencil-alt"></i> <?php _e('System draft'); ?></a>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-5">
            <?php echo $this->form($form, 'inline'); ?>
        </div>
    </div>
    <h3><?php _e('List of stories'); ?></h3>
    <table id="story-list" class="table table-striped table-bordered table-sm">
        <tr>
            <th><?php _e('ID'); ?></th>
            <th><?php _e('Information'); ?></th>
        </tr>
        <?php foreach ($stores as $story) { ?>
            <?php
            if ($story['status'] == 1) {
                $labelClass = 'badge badge-success';
            } elseif ($story['status'] == 5) {
                $labelClass = 'badge badge-danger';
            } else {
                $labelClass = 'badge badge-warning';
            }
            ?>
            <tr>
                <td><span id="label-<?php echo $story['id']; ?>"
                          class="badge badge-default <?php echo $labelClass; ?>"><?php echo $story['id']; ?></span></td>
                <td>
                    <div class="row">
                        <div class="col-md-12">
                            <strong><?php _e('Title'); ?></strong> :
                            <span class="text-danger"> ( <?php echo $this->escape($story['type_view']); ?> ) </span>
                            <?php echo $this->escape($story['title']); ?>
                        </div>
                        <div class="col-md-7 small">
                            <strong><?php _e('Published'); ?></strong>
                            : <?php echo $this->escape($story['time_publish']); ?>
                            <strong><?php _e('By'); ?></strong>
                            : <?php echo $this->escape($story['user']['name']); ?> ( <?php echo $this->escape($story['user']['identity']); ?> )
                        </div>
                        <div class="col-md-5">
                            <strong><?php _e('Action'); ?></strong> :
                            <span class="story-action">
                                <?php if ($story['status'] == 1) { ?>
                                    <a class="btn btn-success btn-sm" title="<?php _e('View'); ?>" href="<?php echo $this->escape($story['storyUrl']); ?>"
                                       target="_blank"><i class="far fa-eye"></i> <?php _e('View'); ?></a>
                                <?php } ?>
                            </span>
                            <div class="btn-group">
                                <button type="button" class="btn btn-primary btn-sm dropdown-toggle"
                                        data-toggle="dropdown">
                                    <i class="fas fa-edit"></i> <?php _e('Manage'); ?>
                                </button>
                                <div class="dropdown-menu" role="menu">
                                    <a class="dropdown-item" title="<?php _e('Edit basic information'); ?>"
                                           href="<?php echo $this->url('', ['action' => 'update', 'id' => $story['id']]); ?>"><i
                                                    class="fas fa-edit"></i> <?php _e('Edit basic information'); ?></a>
                                    <a class="dropdown-item" title="<?php _e('Edit additional information'); ?>"
                                           href="<?php echo $this->url('', ['action' => 'additional', 'id' => $story['id']]); ?>"><i
                                                    class="fas fa-edit"></i> <?php _e('Edit additional information'); ?></a>

                                    <a class="dropdown-item" title="<?php _e('Preview'); ?>"
                                           href="<?php echo $this->url('', ['action' => 'view', 'id' => $story['id']]); ?>"><i
                                                    class="far fa-eye"></i> <?php _e('Preview'); ?></a>
                                </div>
                            </div>
                            <a class="btn btn-danger btn-sm" title="<?php _e('Delete'); ?>"
                               href="<?php echo $this->url('', ['action' => 'delete', 'id' => $story['id']]); ?>"
                               onclick="return confirm('<?php echo _a('Are you sure to delete this story?'); ?>')">
                                <i class="fas fa-trash-alt"></i> <?php _e('Delete'); ?>
                            </a>
                        </div>
                    </div>
                </td>
            </tr>
        <?php } ?>
    </table>
    <div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator'); ?></div>
    <p>
        <span class="badge badge-success"><?php _e('Published'); ?></span>
        <span class="badge badge-warning"><?php _e('Pending review'); ?></span>
        <span class="badge badge-danger"><?php _e('Trash'); ?></span>
    </p>
</div>