<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="news">
	<div class="item">
		<div class="itemHead">
			<span class="itemTitle">
				<h3><?php echo $this->escape($story['title']); ?></h3>
			</span>
		</div>
		<div class="itemInfo">
			<span class="itemPoster"><?php _e('By'); ?>: <?php echo $this->escape($story['uid']); ?></span>
			<span class="itemPostDate"><?php _e('time_update Time'); ?>: <?php echo $this->escape($story['time_publish']); ?></span>
			<span class="itemStats"<?php _e('Read'); ?>: <?php echo $this->escape($story['hits']); ?></span>
			<span class="itemComments"><?php _e('Comments'); ?>: <?php echo $this->escape($story['comments']); ?></span>
			<span class="itemtopics"><?php _e('Topics'); ?>: 
			<?php foreach($topics as $topic) { ?>
				<?php $topic['url'] = $this->url('news',  array('module' => $module, 'controller' => 'topic', 'slug' => $this->escape($topic['slug']))); ?>
				<a title="<?php echo $topic['title']; ?>" href="<?php echo $topic['url']; ?>"><?php echo $topic['title']; ?></a>
			<?php } ?></span>
		   <div class="clearfix"></div>
		</div>
		<div class="itemBody">
			<?php if($story['image']){ ?>
			<div class="itemImage gallery">
				<a href="<?php echo $story['mediumurl']; ?>" title="<?php echo $this->escape($story['imagedes']); ?>"><img src="<?php echo $story['thumburl']; ?>" alt="<?php echo $this->escape($story['title']); ?>" /></a>
			</div>
			<?php } ?>
			<div class="itemText"><?php echo $story['short']; ?></div>
			<div class="itemText"><?php echo $story['body']; ?></div>
			<div class="clearfix"></div>
		</div>
		<div class="itemFoot">
			<p>
				<a class="btn btn-primary" title="<?php _e('Back'); ?>" href="<?php echo $this->url('', array('action' => 'index')); ?>"><i class="fa fa-arrow-left"></i>  <?php _e('Back'); ?></a>
				<a class="btn btn-primary" title="<?php _e('View'); ?>" href="<?php echo $this->url('news',  array('module' => $module, 'controller' => 'story', 'slug' => $this->escape($story['slug']))); ?>"><i class="fa fa-eye"></i> <?php _e('View'); ?></a>
				<a class="btn btn-primary" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', array('action' => 'update', 'id' => $story['id'])); ?>"><i class="fa fa-edit"></i> <?php _e('Edit'); ?></a>
				<a class="btn btn-primary" title="<?php _e('Attach'); ?>" href="<?php echo $this->url('', array('controller' => 'attach', 'action' => 'add', 'id' => $story['id'])); ?>"><i class="fa fa-edit"></i> <?php _e('Attach'); ?></a>
				<a class="btn btn-primary" title="<?php _e('Delete'); ?>" href="<?php echo $this->url('', array('action' => 'delete', 'id' => $story['id'])); ?>"><i class="fa fa-trash-o"></i> <?php _e('Delete'); ?></a>
	    	</p>
		</div>
	</div>
</div>