<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <div class="card bg-light mb-3">
        <div class="card-heading">
            <h3 class="card-title">
                <?php if ($story['important']) { ?>
                    <span class="label badge badge-important">
					<?php _e('Important'); ?>
				</span>
                <?php } ?>
                <?php echo $this->escape($story['title']); ?>
            </h3>
        </div>
        <div class="card-text">
            <div class="itemInfo">
                <span class="itemPostDate"><?php _e('Update Time'); ?>
                    : <?php echo $this->escape($story['time_publish_view']); ?></span>
                <span class="itemStats"><?php _e('Read'); ?>: <?php echo $this->escape($story['hits']); ?></span>
                <span class="itemtopics"><?php _e('Topics'); ?>:
                    <?php foreach ($story['topics'] as $storyTopic) { ?>
                        <a title="<?php echo $storyTopic['title']; ?>"
                           href="<?php echo $storyTopic['url']; ?>"><?php echo $storyTopic['title']; ?></a> ,
				<?php } ?></span>

                <div class="clearfix"></div>
            </div>
            <div class="itemBody">
                <?php if ($story['main_image']) { ?>
                    <div class="itemImage gallery float-left">
                        <img class="img-thumbnail"
                             src="<?php echo Pi::api('doc', 'media')->getSingleLinkUrl($story['main_image'])->setConfigModule('news')->thumb('thumbnail'); ?>"
                             alt="<?php echo $this->escape($story['title']); ?>"/>
                    </div>
                <?php } ?>
                <div class="itemText"><?php echo $story['text_summary']; ?></div>
                <div class="itemText"><?php echo $story['text_description']; ?></div>
                <div class="clearfix"></div>
            </div>
            <div class="clearfix card bg-light mb-3">
                <a class="btn btn-primary" title="<?php _e('Back'); ?>"
                   href="<?php echo $this->url('', ['action' => 'index']); ?>"><i
                            class="fas fa-arrow-left"></i> <?php _e('Back'); ?></a>
                <a class="btn btn-primary" title="<?php _e('View'); ?>"
                   href="<?php echo $this->url('news', ['module' => $module, 'controller' => 'story', 'slug' => $this->escape($story['slug'])]); ?>"><i
                            class="far fa-eye"></i> <?php _e('View'); ?></a>
                <a class="btn btn-primary" title="<?php _e('Edit'); ?>"
                   href="<?php echo $this->url('', ['action' => 'update', 'id' => $story['id']]); ?>"><i
                            class="fas fa-edit"></i> <?php _e('Edit'); ?></a>
                <a class="btn btn-primary" title="<?php _e('Delete'); ?>"
                   href="<?php echo $this->url('', ['action' => 'delete', 'id' => $story['id']]); ?>"><i
                            class="far fa-trash-alt"></i> <?php _e('Delete'); ?></a>
            </div>
        </div>
    </div>
</div>