<?php
$this->css(array(
    $this->assetModule('css/admin.css'),
    $this->assetModule('script/system-ui.css', 'system'),
));
$this->jQuery();
$this->js($this->assetModule('script/system-msg.js', 'system'));
?>
<div class="clearfix">
    <div class="admin-header clearfix row">
        <div class="col-md-12">
            <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
                <div class="panel panel-default">
                    <div class="panel-heading" role="tab" id="headingHelp">
                        <h4 class="panel-title">
                            <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseHelp" aria-expanded="false" aria-controls="collapseHelp">
                                <i class="fa fa-plus"></i> <?php _e('Description about add new story'); ?>
                            </a>
                        </h4>
                    </div>
                    <div id="collapseHelp" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingHelp">
                        <div class="panel-body">
                            <p><?php _e('You can select many types on submit new story, each type have different template and view and useful for special usage'); ?></p>
                            <dl class="dl-horizontal">
                                <dt><strong class="text-danger"><?php _e('Text'); ?></strong></dt>
                                <dd><?php _e('Text type, default view format main image set on center and under title and extra images and information set on sidebar'); ?></dd>
                            </dl>
                            <dl class="dl-horizontal">
                                <dt><strong class="text-danger"><?php _e('Article'); ?></strong></dt>
                                <dd><?php _e('Article view, main image and extra information set on sidebar and text set on center and under title'); ?></dd>
                            </dl>
                            <dl class="dl-horizontal">
                                <dt><strong class="text-danger"><?php _e('Magazine'); ?></strong></dt>
                                <dd><?php _e('Magazine view, main and extra images set on center and text under them , after that extra information , without sidebar'); ?></dd>
                            </dl>
                            <dl class="dl-horizontal">
                                <dt><strong class="text-danger"><?php _e('Blog post'); ?></strong></dt>
                                <dd><?php _e('You need install blog module and story show on blog system, for better SEO'); ?></dd>
                            </dl>
                            <dl class="dl-horizontal">
                                <dt><strong class="text-danger"><?php _e('Image'); ?></strong></dt>
                                <dd><?php _e('Single image set on center and under title, other texts , extra information and images set under main and big image, you can use topic as gallery album and each story is single image on album'); ?></dd>
                            </dl>
                            <dl class="dl-horizontal">
                                <dt><strong class="text-danger"><?php _e('Gallery'); ?></strong></dt>
                                <dd><?php _e('Gallery album view, main image and other extra images set as album on same position, all other texts and extra information set under images, you can use topic as category for albums and each story is single album by images'); ?></dd>
                            </dl>
                            <dl class="dl-horizontal">
                                <dt><strong class="text-danger"><?php _e('Media'); ?></strong></dt>
                                <dd><?php _e('Media type load video or audio player under title and set all extra information on side bar and texts under player, you need attach mp4 or mp3 files to story or make audio / video attribute and put your media file link'); ?></dd>
                            </dl>
                            <dl class="dl-horizontal">
                                <dt><strong class="text-danger"><?php _e('Download'); ?></strong></dt>
                                <dd><?php _e('Download template and show download button for get file by user, you need attach file to story or make file attribute and put your file link'); ?></dd>
                            </dl>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-7">
            <div class="nav">
                <div class="btn-group">
                    <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-plus"></i> <?php _e('Add new story'); ?> <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu">
                        <?php if (!$config['admin_deactivate_view']) { ?>
                            <li><a title="<?php _e('Add new text'); ?>"
                                   href="<?php echo $this->url('', array('controller' => 'story', 'action' => 'add', 'type' => 'text')); ?>"><i
                                        class="fa fa-sticky-note"></i> <?php _e('Add new text'); ?></a></li>
                            <li><a title="<?php _e('Add new article'); ?>"
                                   href="<?php echo $this->url('', array('controller' => 'story', 'action' => 'add', 'type' => 'article')); ?>"><i
                                        class="fa fa-folder"></i> <?php _e('Add new article'); ?></a></li>
                            <li><a title="<?php _e('Add new magazine'); ?>"
                                   href="<?php echo $this->url('', array('controller' => 'story', 'action' => 'add', 'type' => 'magazine')); ?>"><i
                                        class="fa fa-pie-chart"></i> <?php _e('Add new magazine'); ?></a></li>
                            <li><a title="<?php _e('Add new gallery album'); ?>"
                                   href="<?php echo $this->url('', array('controller' => 'story', 'action' => 'add', 'type' => 'gallery')); ?>"><i
                                        class="fa fa-camera"></i> <?php _e('Add new gallery album'); ?></a></li>
                            <li><a title="<?php _e('Add new single image'); ?>"
                                   href="<?php echo $this->url('', array('controller' => 'story', 'action' => 'add', 'type' => 'image')); ?>"><i
                                        class="fa fa-picture-o"></i> <?php _e('Add new single image'); ?></a></li>
                            <li><a title="<?php _e('Add new media'); ?>"
                                   href="<?php echo $this->url('', array('controller' => 'story', 'action' => 'add', 'type' => 'media')); ?>"><i
                                        class="fa fa-video-camera"></i> <?php _e('Add new media'); ?></a></li>
                            <li><a title="<?php _e('Add new download'); ?>"
                                   href="<?php echo $this->url('', array('controller' => 'story', 'action' => 'add', 'type' => 'download')); ?>"><i
                                        class="fa fa-download"></i> <?php _e('Add new download'); ?></a></li>
                        <?php } ?>
                        <?php if (Pi::service('module')->isActive('blog')) { ?>
                            <li><a title="<?php _e('Add new blog post'); ?>"
                                   href="<?php echo $this->url('', array('controller' => 'story', 'action' => 'add', 'type' => 'post')); ?>"><i
                                        class="fa fa-globe"></i> <?php _e('Add new blog post'); ?></a></li>
                        <?php } ?>
                        <?php if (!Pi::service('module')->isActive('blog') && $config['admin_deactivate_view']) { ?>
                            <li><?php _e('News module front page is deactivate'); ?></li>
                        <?php } ?>
                    </ul>
                </div>
                <div class="btn-group">
                    <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown">
                        <i class="fa fa-eye"></i> <?php _e('View'); ?> <span class="caret"></span>
                    </button>
                    <ul class="dropdown-menu" role="menu">
                        <li><a title="<?php _e('All stories'); ?>"
                               href="<?php echo $this->url('', array('controller' => 'story', 'action' => 'index')); ?>"><i
                                    class="fa fa-file"></i> <?php _e('All stories'); ?></a></li>
                        <li><a title="<?php _e('Published'); ?>"
                               href="<?php echo $this->url('', array('controller' => 'story', 'action' => 'index', 'status' => '1')); ?>"><i
                                    class="fa fa-file"></i> <?php _e('Published'); ?></a></li>
                        <li><a title="<?php _e('Pending review'); ?>"
                               href="<?php echo $this->url('', array('controller' => 'story', 'action' => 'index', 'status' => '2')); ?>"><i
                                    class="fa fa-file"></i> <?php _e('Pending review'); ?></a></li>
                        <li><a title="<?php _e('Draft'); ?>"
                               href="<?php echo $this->url('', array('controller' => 'story', 'action' => 'index', 'status' => '3')); ?>"><i
                                    class="fa fa-file"></i> <?php _e('Draft'); ?></a></li>
                        <li><a title="<?php _e('Private'); ?>"
                               href="<?php echo $this->url('', array('controller' => 'story', 'action' => 'index', 'status' => '4')); ?>"><i
                                    class="fa fa-file"></i> <?php _e('Private'); ?></a></li>
                        <li><a title="<?php _e('Trash'); ?>"
                               href="<?php echo $this->url('', array('controller' => 'story', 'action' => 'index', 'status' => '5')); ?>"><i
                                    class="fa fa-trash"></i> <?php _e('Trash'); ?></a></li>
                        <li><a title="<?php _e('System draft'); ?>"
                               href="<?php echo $this->url('', array('controller' => 'story', 'action' => 'index', 'status' => '6')); ?>"><i
                                    class="fa fa-pencil"></i> <?php _e('System draft'); ?></a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="col-md-5">
            <?php echo $this->form($form, 'inline'); ?>
        </div>
    </div>
    <h3><?php _e('List of stories'); ?></h3>
    <table id="story-list" class="table table-striped table-bordered table-condensed">
        <tr>
            <th><?php _e('ID'); ?></th>
            <th><?php _e('Information'); ?></th>
        </tr>
        <?php foreach ($stores as $story) { ?>
            <?php
            if ($story['status'] == 1) {
                $labelClass = 'label label-success';
            } elseif ($story['status'] == 5) {
                $labelClass = 'label label-danger';
            } else {
                $labelClass = 'label label-warning';
            }
            ?>
            <tr>
                <td><span id="label-<?php echo $story['id']; ?>"
                          class="label label-default <?php echo $labelClass; ?>"><?php echo $story['id']; ?></span></td>
                <td>
                    <div class="row">
                        <div class="col-md-12">
                            <strong><?php _e('Title'); ?></strong> :
                            <span class="text-danger"> ( <?php echo $this->escape($story['type_view']); ?> ) </span>
                            <?php echo $this->escape($story['title']); ?>
                        </div>
                        <div class="col-md-7 small">
                            <strong><?php _e('Published'); ?></strong>
                            : <?php echo $this->escape($story['time_publish']); ?>
                            <strong><?php _e('By'); ?></strong>
                            : <?php echo $this->escape($story['user']['name']); ?> ( <?php echo $this->escape($story['user']['identity']); ?> )
                        </div>
                        <div class="col-md-5">
                            <strong><?php _e('Action'); ?></strong> :
                            <span class="story-action">
                                <?php if ($story['status'] == 1) { ?>
                                    <a class="btn btn-success btn-xs" title="<?php _e('View'); ?>" href="<?php echo $this->escape($story['storyUrl']); ?>" target="_blank"><i class="fa fa-eye"></i>  <?php _e('View'); ?></a>
                                <?php } ?>
                                <?php if ($story['status'] == 1) { ?>
                                    <button id="button-<?php echo $story['id']; ?>" type="button"
                                            class="btn btn-warning btn-xs" data-toggle="button"
                                            data-link="<?php echo $this->url('', array('action' => 'accept', 'id' => $story['id'], 'status' => '2')); ?>">
                                        <i class="fa fa-trash-o"></i> <?php _e('Reject'); ?></button>
                                <?php } elseif (in_array($story['status'], array(2, 3, 4))) { ?>
                                    <button id="button-<?php echo $story['id']; ?>" type="button"
                                            class="btn btn-success btn-xs" data-toggle="button"
                                            data-link="<?php echo $this->url('', array('action' => 'accept', 'id' => $story['id'], 'status' => '1')); ?>">
                                        <i class="fa fa-check"></i> <?php _e('Accept'); ?></button>
                                <?php } ?>
                            </span>
                            <div class="btn-group">
                                <button type="button" class="btn btn-primary btn-xs dropdown-toggle"
                                        data-toggle="dropdown">
                                    <i class="fa fa-edit"></i> <?php _e('Manage'); ?> <span class="caret"></span>
                                </button>
                                <ul class="dropdown-menu" role="menu">
                                    <li><a title="<?php _e('Edit basic information'); ?>"
                                           href="<?php echo $this->url('', array('action' => 'update', 'id' => $story['id'])); ?>"><i
                                                class="fa fa-edit"></i> <?php _e('Edit basic information'); ?></a></li>
                                    <li><a title="<?php _e('Edit additional information'); ?>"
                                           href="<?php echo $this->url('', array('action' => 'additional', 'id' => $story['id'])); ?>"><i
                                                class="fa fa-edit"></i> <?php _e('Edit additional information'); ?></a>
                                    </li>
                                    <li><a title="<?php _e('Preview'); ?>"
                                           href="<?php echo $this->url('', array('action' => 'view', 'id' => $story['id'])); ?>"><i
                                                class="fa fa-eye"></i> <?php _e('Preview'); ?></a></li>
                                </ul>
                            </div>
                            <a class="btn btn-danger btn-xs" title="<?php _e('Delete'); ?>" href="<?php echo $this->url('', array('action' => 'delete', 'id' => $story['id'])); ?>"   onclick="return confirm('<?php echo _a('Are you sure to delete this story?'); ?>')">
                                <i class="fa fa-trash"></i>  <?php _e('Delete'); ?>
                            </a>
                        </div>
                    </div>
                </td>
            </tr>
        <?php } ?>
    </table>
    <div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator'); ?></div>
    <p>
        <span class="label label-success"><?php _e('Published'); ?></span>
        <span class="label label-warning"><?php _e('Pending review'); ?></span>
        <span class="label label-danger"><?php _e('Trash'); ?></span>
    </p>
</div>
<script>
    (function ($) {
        $("#story-list").on("click", ".story-action button", function () {
            systemMessage.wait("<?php _e('Accept story in process'); ?>");
            $.getJSON($(this).attr("data-link")).done(function (result) {
                if (result.ajaxstatus == 1) {
                    if (result.storystatus == 1) {
                        var labelClass = 'label label label-success';
                        var buttonClass = 'btn btn-warning btn-xs disabled';
                        var buttonText = '<i class="fa fa-trash-o"></i> <?php _e("Reject"); ?>';
                    }
                    if (result.storystatus == 2) {
                        var labelClass = 'label label label-warning';
                        var buttonClass = 'btn btn-success btn-xs disabled';
                        var buttonText = '<i class="fa fa-check"></i> <?php _e("Accept"); ?>';
                    }
                    $('#label-' + result.id).attr('class', labelClass);
                    $('#button-' + result.id).attr('class', buttonClass).html(buttonText);
                    ;
                    systemMessage.succ(result.message);
                } else {
                    systemMessage.fail(result.message);
                }
            });
        });
    })(jQuery)
</script>