<?php
    $this->css(array(
        $this->assetModule('css/admin.css'),
        $this->assetModule('script/system-ui.css', 'system'),
    ));
    $this->jQuery();
    $this->js($this->assetModule('script/system-msg.js', 'system'));
?>
<div class="news">
	<h2><?php echo $this->escape($title); ?></h2>
	<div id="story-form">
	<?php include $this->templateComponent('forms'); ?>
	</div>
</div> 
<script type="text/javascript">
(function($){
    $("#story-form").on("click","button",function(){
       systemMessage.wait("<?php _e('Remove image story in process'); ?>");
       $.getJSON($(this).attr("data-link")).done(function(result){
          if(result.status==1){
             systemMessage.succ(result.message);
          }else{
             systemMessage.fail(result.message);
          }
       });
    });
})(jQuery)
</script>

