<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="news">
	<p>
		<a class="btn btn-danger" title="<?php _e('Rebuild'); ?>" href="<?php echo $this->url('', array('action' => 'rebuild')); ?>"><i class="fa fa-repeat"></i> <?php _e('Rebuild'); ?></a>
		<a class="btn btn-danger" title="<?php _e('Prune'); ?>" href="<?php echo $this->url('', array('action' => 'prune')); ?>"><i class="fa fa-trash-o"></i> <?php _e('Prune'); ?></a>
		<a class="btn btn-danger" title="<?php _e('Spotlight'); ?>" href="<?php echo $this->url('', array('action' => 'spotlight')); ?>"><i class="fa fa-building-o"></i> <?php _e('Spotlight'); ?></a>
		<a class="btn btn-danger" title="<?php _e('Page'); ?>" href="<?php echo $this->url('', array('action' => 'page')); ?>"><i class="fa fa-file-o"></i> <?php _e('Page'); ?></a>
		<a class="btn btn-danger" title="<?php _e('Sitemap'); ?>" href="<?php echo $this->url('', array('action' => 'sitemap')); ?>"><i class="fa fa-sitemap"></i> <?php _e('Sitemap'); ?></a>
		<a class="btn btn-danger" title="<?php _e('Image'); ?>" href="<?php echo $this->url('', array('action' => 'image')); ?>"><i class="fa fa-picture-o"></i> <?php _e('Image'); ?></a>
	</p>
	<h3><?php echo $this->escape($title); ?></h3>
	<div class="alert alert-success"><?php echo $this->escape($message); ?></div>
</div>