<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="news">
	<p>
		<a class="btn btn-danger" title="<?php _e('Rebuild'); ?>" href="<?php echo $this->url('', array('action' => 'rebuild')); ?>"><i class="fa fa-repeat"></i> <?php _e('Rebuild'); ?></a>
		<a class="btn btn-danger" title="<?php _e('Prune'); ?>" href="<?php echo $this->url('', array('action' => 'prune')); ?>"><i class="fa fa-trash-o"></i> <?php _e('Prune'); ?></a>
		<a class="btn btn-danger" title="<?php _e('Writer'); ?>" href="<?php echo $this->url('', array('action' => 'writer')); ?>"><i class="fa fa-user"></i> <?php _e('Writer'); ?></a>
		<a class="btn btn-danger" title="<?php _e('Spotlight'); ?>" href="<?php echo $this->url('', array('action' => 'spotlight')); ?>"><i class="fa fa-user"></i> <?php _e('Spotlight'); ?></a>
	</p>
	<h3><?php echo $this->escape($title); ?></h3>
	<div class="alert alert-success"><?php echo $this->escape($message); ?></div>
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<th><?php _e('Writer'); ?></th>
			<th><?php _e('Count'); ?></th>
		</tr>
	<?php foreach($writers as $writer) { ?>
	   <tr>
		   <td><?php echo $this->escape($writer['uid']); ?></td>
	      <td><?php echo $this->escape($writer['count']); ?></td>
	   </tr>   
	<?php } ?> 
	</table>
</div>