<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="news">
	<p>
	   <a class="btn" title="<?php _e('Add Topic'); ?>" href="<?php echo $this->url('', array('controller' => 'topic', 'action' => 'update')); ?>"><i class="icon-folder-open"></i> <?php _e('Add Topic'); ?></a>
	</p>
	<h3><?php _e('List of topics'); ?></h3>
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<th><?php _e('ID'); ?></th>
			<th><?php _e('Title'); ?></th>
			<th><?php _e('Option Type'); ?></th>
			<th><?php _e('Action'); ?></th>
		</tr>
		<?php foreach($topics as $topic) { ?>
		<?php
		if($topic['status'] == 1) {
			$labelIdClass = 'label-success';	
		} else {
			$labelIdClass = 'label-warning';	
		}	
		?>
		<?php
		if($topic['topic_type'] == 'topic') {
			$labelTypeClass = 'label-success';	
		} else {
			$labelTypeClass = 'label-warning';	
		}			
		?>
		<tr>
			<td><span class="label <?php echo $labelIdClass; ?>"><?php echo $this->escape($topic['id']); ?></span></td>
			<td><?php echo $this->escape($topic['title']); ?></td>
			<td><span class="label <?php echo $labelTypeClass; ?>"><?php 
			if($topic['topic_type'] == 'topic') {
				$type = _e('Topic Options');
			} else {
				$type = _e('Module Options');
			}		
			?></span></td>
			<td>
					<a class="btn" title="<?php _e('View'); ?>" href="<?php echo $this->url('.news',  array('module' => $module, 'controller' => 'topic', 'slug' => $this->escape($topic['slug']))); ?>"><i class="icon-eye-open"></i> <?php _e('View'); ?></a>
					<a class="btn" title="<?php _e('All stories'); ?>" href="<?php echo $this->url('', array('controller' => 'story', 'action' => 'index', 'topic' => $topic['id'])); ?>"><i class="icon-eye-open"></i> <?php _e('All stories'); ?></a>
					<a class="btn" title="<?php _e('Manager'); ?>" href="<?php echo $this->url('', array('controller' => 'moderator', 'action' => 'topic', 'id' => $topic['id'])); ?>"><i class="icon-user"></i> <?php _e('Manager'); ?></a>
					<a class="btn" title="<?php _e('Edit'); ?>" href="<?php echo $this->url('', array('action' => 'update', 'id' => $topic['id'])); ?>"><i class="icon-edit"></i> <?php _e('Edit'); ?></a>
					<a class="btn" title="<?php _e('Delete'); ?>" href="<?php echo $this->url('', array('action' => 'delete', 'id' => $topic['id'])); ?>"><i class="icon-trash"></i> <?php _e('Delete'); ?></a>
			</td>
		</tr>
		<?php } ?>
	</table>
	<div class="paginator"><?php echo $this->paginationControl($topics, 'Sliding', 'paginator'); ?></div>
</div>