<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="clearfix">
    <p>
        <a class="btn btn-primary" title="<?php _e('Add Topic'); ?>"
           href="<?php echo $this->url('', ['controller' => 'topic', 'action' => 'update']); ?>"><i
                    class="fas fa-folder-open"></i><?php _e('Add Topic'); ?></a>
    </p>

    <h3><?php _e('List of topics'); ?></h3>
    <table class="table table-striped table-bordered table-sm">
        <tr>
            <th><?php _e('ID'); ?></th>
            <th><?php _e('Title'); ?></th>
            <th><?php _e('Style'); ?></th>
            <th><?php _e('Module'); ?></th>
            <th><?php _e('Action'); ?></th>
        </tr>
        <?php foreach ($topics as $topic) { ?>
            <?php
            if ($topic['status'] == 1) {
                $labelClass = 'label-success';
            } elseif ($topic['status'] == 5) {
                $labelClass = 'label-danger';
            } else {
                $labelClass = 'label-warning';
            }
            ?>
            <tr>
                <td><span class="label <?php echo $labelClass; ?>"><?php echo $this->escape($topic['id']); ?></span>
                </td>
                <td><?php echo $this->escape($topic['title']); ?></td>
                <td><?php echo $this->escape($topic['style_view']); ?></td>
                <td><?php echo $this->escape($topic['type_view']); ?></td>
                <td>
                    <a class="btn btn-success btn-sm" title="<?php _e('View'); ?>"
                       href="<?php echo $this->url('news', ['module' => $module, 'controller' => 'topic', 'slug' => $this->escape($topic['slug'])]); ?>">
                        <i class="far fa-eye"></i> <?php _e('View'); ?>
                    </a>
                    <a class="btn btn-primary btn-sm" title="<?php _e('All stories'); ?>"
                       href="<?php echo $this->url('', ['controller' => 'story', 'action' => 'index', 'topic' => $topic['id']]); ?>">
                        <i class="far fa-eye"></i> <?php _e('All stories'); ?>
                    </a>
                    <a class="btn btn-primary btn-sm" title="<?php _e('Edit'); ?>"
                       href="<?php echo $this->url('', ['action' => 'update', 'id' => $topic['id']]); ?>">
                        <i  class="fas fa-edit"></i> <?php _e('Edit'); ?>
                    </a>
                </td>
            </tr>
        <?php } ?>
    </table>
    <div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?></div>
    <p>
        <span class="badge badge-success"><?php _e('Published'); ?></span>
        <span class="badge badge-warning"><?php _e('Pending review'); ?></span>
        <span class="badge badge-danger"><?php _e('Trash'); ?></span>
    </p>
</div>