<?php $this->css($this->assetModule('css/admin.css')); ?>
<div class="news">
	<div class="btn-group">
	   <a class="btn btn-primary" title="<?php _e('Add Story'); ?>" href="<?php echo $this->url('', array('controller' => 'story', 'action' => 'update')); ?>"><i class="fa fa-file"></i> <?php _e('Add Story'); ?></a>
	   <a class="btn btn-primary" title="<?php _e('Add Topic'); ?>" href="<?php echo $this->url('', array('controller' => 'topic', 'action' => 'update')); ?>"><i class="fa fa-folder-open"></i> <?php _e('Add Topic'); ?></a>
	   <a class="btn btn-primary" title="<?php _e('Add Moderator'); ?>" href="<?php echo $this->url('', array('controller' => 'moderator', 'action' => 'update')); ?>"><i class="fa fa-user"></i> <?php _e('Add Moderator'); ?></a>
	   <a class="btn btn-primary" title="<?php _e('Add Spotlight'); ?>" href="<?php echo $this->url('', array('controller' => 'spotlight', 'action' => 'update')); ?>"><i class="fa fa-user"></i> <?php _e('Add Spotlight'); ?></a>
	   <a class="btn btn-primary" title="<?php _e('Add Extra'); ?>" href="<?php echo $this->url('', array('controller' => 'extra', 'action' => 'update')); ?>"><i class="fa fa-random"></i> <?php _e('Add Extra'); ?></a>
	</div>
	<br />
	<p>Not Yet</p>
</div>