<?php

// Add StickyJs
$this->js($this->assetModule('js/jquery.hc-sticky.js'));

$script = <<<'EOT'
$(document).ready(function(){
    $(".news-story-page-side").hcSticky({
        responsive : true,
        top: $('#pi-header nav').height() + 20,
        stickTo: $('.news-story-page'),
        offResolutions: -992
    });
    
    $('.news-story-page-side div.modal').insertAfter('.wrapper-sticky');
  });
EOT;

$this->headScript()->appendScript($script);