<?php $this->css($this->assetModule('css/block.css', 'news')); ?>
<div class="itemBlock itemBlockitem">
	<?php foreach($block['resources'] as $story) { ?>
	<div class="media">
		<?php if($block['showimage'] && !empty($story['thumbUrl'])){ ?>
		<a class="pull-left itemImage" href="<?php echo $this->escape($story['storyUrl']); ?>">
			<img src="<?php echo $story['thumbUrl']; ?>" alt="<?php echo $this->escape($story['title']); ?>" class="media-object img-thumbnail"  />
        </a>
        <?php } ?>
        <div class="media-body">
        	<h4 class="media-heading"><a href="<?php echo $this->escape($story['storyUrl']); ?>" title="<?php echo $this->escape($story['title']); ?>"><?php echo $this->escape($story['title']); ?></a></h4>
        	<?php if($block['showdate'] || $block['showhits']){ ?>
			<div class="itemInfo">
				<?php if($block['showdate']){ ?><span class="itemPostDate"><?php _e('Time'); ?> : <?php echo $this->escape($story['time_publish_view']); ?></span><?php } ?>
				<?php if($block['showhits']){ ?><span class="itemStats"><?php _e('Read'); ?> : <?php echo $this->escape($story['hits']); ?></span><?php } ?>
			</div>
			<?php } ?>
        	<?php if($block['showdesc']){ echo $story['short']; } ?>
        	<?php if($block['showmore']){ ?>
            <p><a href="<?php echo $this->escape($story['storyUrl']); ?>" title="<?php echo $this->escape($story['title']); ?>"><?php _e('Read More'); ?></a></p>
        	<?php } ?>
        </div>	
    </div>
	<?php } ?>
	<?php if ($block['showblockmore']) { ?>
    <div class="itemBlockLink">
    	<a title="<?php _e('read more'); ?>" href="<?php echo $block['linkblockmore']; ?>"><?php _e('read more'); ?></a>
    </div>
	<?php } ?>
</div>