<div class="news-block">
    <?php if ($block['microblog_active']) { ?>
        <div class="news-microblog-post clearfix">
            <?php foreach ($block['resources'] as $microblog) { ?>
                <div class="media single-post">
                    <div class="media-body">
                        <?php if ($microblog['topic'] == 0) { ?>
                            <div class="clearfix">
                                <ul class="list-inline">
                                    <li class="list-inline-item">
                                        <div class="text-center">
                                            <a href="<?php echo $microblog['profileUrl']; ?>" title="<?php echo $microblog['user']['name']; ?>">
                                                <?php echo $microblog['user']['avatar']; ?>
                                            </a>
                                        </div>
                                    </li>
                                    <li class="list-inline-item">
                                        <a href="<?php echo $microblog['profileUrl']; ?>" title="<?php echo $microblog['user']['name']; ?>">
                                            <?php echo $microblog['user']['name']; ?>
                                        </a>
                                    </li>
                                    <li class="list-inline-item">
                                        <a href="<?php echo $microblog['microblogUrl']; ?>" title="<?php echo $microblog['seo_title']; ?>">
                                            <?php echo $microblog['time_create_view']; ?>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        <?php } ?>
                        <div class="clearfix">
                            <?php echo $microblog['post']; ?>
                        </div>
                    </div>
                </div>
            <?php } ?>
        </div>
    <?php } else { ?>
        <div class="alert alert-danger" role="alert">
            <?php echo _b('Microblog system is inactive.'); ?>
        </div>
    <?php } ?>
</div>