<div class="clearfix">
    <div class="index-post">
        <?php foreach ($block['resources'] as $microblog) { ?>
            <div class="media single-post">
                <div class="col-md-3">
                    <div class="text-center">
                        <p>
                            <a href="<?php echo $microblog['profileUrl']; ?>" title="<?php echo $microblog['user']['name']; ?>">
                                <?php echo $microblog['user']['avatar']; ?>
                            </a>
                        </p>
                        <p>
                            <a href="<?php echo $microblog['profileUrl']; ?>" title="<?php echo $microblog['user']['name']; ?>">
                                <?php echo $microblog['user']['name']; ?>
                            </a>
                        </p>
                        <p>
                            <a href="<?php echo $microblog['microblogUrl']; ?>" title="<?php echo $microblog['seo_title']; ?>">
                                <?php echo $microblog['time_create_view']; ?>
                            </a>
                        </p>
                    </div>
                </div>
                <div class="media-body col-md-9">
                    <div class="clearfix">
                        <?php echo $microblog['post']; ?>
                    </div>
                </div>
            </div>
        <?php } ?>
    </div>
</div>