<div class="news-block news-spotlight-block">
    <?php foreach ($block['resources'] as $resources) { ?>
        <div class="row" itemscope itemtype="http://schema.org/Article">
            <div class="col-md-12 col-sm-12 col-xs-12 text-center">
                <h3 itemprop="name"><?php echo $this->escape($resources['topic']['title']); ?></h3>
                <?php if ($block['showtopicimage'] && !empty($resources['topic']['thumbUrl'])) { ?>
                    <a itemprop="url" title="<?php echo $this->escape($resources['topic']['title']); ?>"
                       href="<?php echo $this->escape($resources['topic']['topicUrl']); ?>">
                        <img itemprop="image" src="<?php echo $this->escape($resources['topic']['mediumUrl']); ?>"
                             alt="<?php echo $this->escape($resources['topic']['title']); ?>" class="img-thumbnail"/>
                    </a>
                <?php } ?>
            </div>
            <div class="col-md-12 col-sm-12 col-xs-12">
                <ul class="list-unstyled" itemscope itemtype="http://schema.org/ItemList">
                    <?php foreach ($resources['story'] as $story) { ?>
                        <li itemprop="itemListElement">
                            <a itemprop="name" href="<?php echo $this->escape($story['storyUrl']); ?>"
                               title="<?php echo $this->escape($story['title']); ?>"><?php echo $this->escape($story['title']); ?></a>
                        </li>
                    <?php } ?>
                </ul>
            </div>
            <div class="col-md-12 col-sm-12 col-xs-12">
                <a itemprop="url" title="<?php echo $this->escape($resources['topic']['title']); ?>"
                   href="<?php echo $this->escape($resources['topic']['topicUrl']); ?>"><?php echo _b('Read More'); ?></a>
            </div>
        </div>
        <div class="clearfix"></div>
    <?php } ?>
</div>