<?php $this->css([$this->assetModule('css/block.css', 'news') => ['defer' => 'defer']]); ?>
<div class="news-block">
    <div class="news-item-block itemList clearfix">
        <?php

        if ($block['type'] == 'vertical') {
            $template = $this->template('story-vertical.phtml', 'widget', 'news');
        } elseif ($block['type'] == 'verticalwide') {
            $template = $this->template('story-vertical-wide.phtml', 'widget', 'news');
        } elseif ($block['type'] == 'verticalcompressed') {
            $template = $this->template('story-vertical-compressed.phtml', 'widget', 'news');
        } elseif ($block['type'] == 'horizontal') {
            $template = $this->template('story-horizontal.phtml', 'widget', 'news');
        } elseif ($block['type'] == 'list') {
            $template = $this->template('story-list.phtml', 'widget', 'news');
        } elseif ($block['type'] == 'table') {
            $template = $this->template('story-table.phtml', 'widget', 'news');
        } elseif ($block['type'] == 'slide') {
            $template = $this->template('story-slide.phtml', 'widget', 'news');
        } elseif ($block['type'] == 'slidehover') {
            $template = $this->template('story-slide.phtml', 'widget', 'news');
        } elseif ($block['type'] == 'carousel') {
            $template = $this->template('story-carousel.phtml', 'widget', 'news');
        } elseif ($block['type'] == 'image') {
            $template = $this->template('story-image.phtml', 'widget', 'news');
        } elseif ($block['type'] == 'magazine') {
            $template = $this->template('story-magazine.phtml', 'widget', 'news');
        } elseif ($block['type'] == 'magazinewide') {
            $template = $this->template('story-magazine-wide.phtml', 'widget', 'news');
        } else {
            $template = $this->template('story-vertical.phtml', 'widget', 'news');
        }

        include $template;
        ?>
        <?php if ($block['showblockmore']) { ?>
            <div class="news-block-more clearfix">
                <a class="float-right" title="<?php echo _b('More stories'); ?>" href="<?php echo $block['linkblockmore']; ?>">
                    <?php echo _b('More stories'); ?>
                </a>
            </div>
        <?php } ?>
    </div>
</div>