<?php $this->css($this->assetModule('css/block.css', 'news')); ?>
<div class="itemBlock itemBlockTable">
	<table class="table table-striped table-bordered table-condensed">
		<tr char="head">
			<th><?php _b('Title'); ?></th>
			<?php if($block['showdesc']){ ?><th><?php _b('Short Info'); ?></th><?php } ?>
			<?php if($block['showdate']){ ?><th><?php _b('Time'); ?></th><?php } ?>
			<?php if($block['showhits']){ ?><th><?php _b('Read'); ?></th><?php } ?>
		</tr>
		<?php foreach($block['resources'] as $story) { ?>
		<tr class="odd">
			<td><a href="<?php echo $this->escape($story['storyUrl']); ?>" title="<?php echo $this->escape($story['title']); ?>"><?php echo $this->escape($story['title']); ?></a></td>
			<?php if($block['showdesc']){ ?><td><?php echo $this->escape($story['short']); ?></td><?php } ?>
			<?php if($block['showdate']){ ?><td><?php echo $this->escape($story['time_publish_view']); ?></td><?php } ?>
			<?php if($block['showhits']){ ?><td><?php echo $this->escape($story['hits']); ?></td><?php } ?>
		</tr>
		<?php } ?>
	</table>
	<?php if ($block['showblockmore']) { ?>
    <div class="itemBlockLink">
    	<a title="<?php _b('Read More'); ?>" href="<?php echo $block['linkblockmore']; ?>"><?php _b('Read More'); ?></a>
    </div>
	<?php } ?>
</div>