<?php $this->css($this->assetModule('css/block.css', 'news')); ?>
<div class="categoryBlock categoryBlockList">
	<div class="itemList">
		<ul>
		<?php foreach($block['resources'] as $topic) { ?>
			<li>
				<span class="itemTitle"><a href="<?php echo $this->url($module . '-news', array('module' => $module ,'controller' => 'topic' ,'slug' => $this->escape($topic['slug']))); ?>" title="<?php echo $this->escape($topic['title']); ?>"><?php echo $this->escape($topic['title']); ?></a></span>
			</li>
		<?php } ?>
		<div class="clearfix"></div>
		</ul>
	</div>
	<?php if ($block['showblockmore']) { ?>
    <div class="itemBlockLink">
    	<a title="<?php _e('read more'); ?>" href="<?php echo $block['linkblockmore']; ?>"><?php _e('read more'); ?></a>
    </div>
	<?php } ?>
</div> 
