<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="news">
	<?php if(!empty($config['advertisement'])){ ?><div class="itemAds"><?php echo $config['advertisement']; ?></div><?php } ?>
	<div class="page-message">
		<div class="alert alert-block ">
			<h4 class="alert-heading"><?php _e('Archive'); ?></h4>
			<p><?php echo $message; ?></p>
		</div>
	</div>
	<div class="btn-toolbar">
		<div class="btn-group">
			<a class="btn" title="<?php echo $this->escape($date['prev-month']); ?>" href="<?php echo $this->escape($url['prev-month']); ?>"><?php echo $this->escape($date['prev-month']); ?></a>
			<a class="btn btn-info" title="<?php echo $this->escape($month); ?>"><?php echo $this->escape($month); ?></a>
			<a class="btn" title="<?php echo $this->escape($date['next-month']); ?>" href="<?php echo $this->escape($url['next-month']); ?>"><?php echo $this->escape($date['next-month']); ?></a>
		</div>
		<div class="btn-group">
			<a class="btn" title="<?php echo $this->escape($date['prev-year']); ?>" href="<?php echo $this->escape($url['prev-year']); ?>"><?php echo $this->escape($date['prev-year']); ?></a>
			<a class="btn btn-info" title="<?php echo $this->escape($year); ?>"><?php echo $this->escape($year); ?></a>
			<a class="btn" title="<?php echo $this->escape($date['next-year']); ?>" href="<?php echo $this->escape($url['next-year']); ?>"><?php echo $this->escape($date['next-year']); ?></a>
		</div>
	</div>
	<?php if(!empty($stores)) { ?>
	<table class="table table-striped table-bordered table-condensed">
		<tr>
			<th><?php _e('Stroy'); ?></th>
			<th><?php _e('Hits'); ?></th>
			<th><?php _e('Date'); ?></th>
		</tr>
	   <?php foreach($stores as $story) { ?>
	   <tr>
			<td><a title="<?php echo $this->escape($story['title']); ?>" href="<?php echo $this->url('.news', array('module' => $module ,'controller' => 'story' ,'slug' => $this->escape($story['slug']))); ?>"><?php echo $this->escape($story['title']); ?></a></td>
			<td><?php echo $this->escape($story['hits']); ?></td>
			<td><?php echo $this->escape($story['publish']); ?></td>
		</tr>	
		<?php	} ?>
	</table>
	<div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator'); ?></div>
	<?php } ?>
</div>