<?php if (isset($archive) && !empty($archive)) { ?>
<div class="archive">
	<div class="page-message">
		<div class="alert alert-block">
			<h4 class="alert-heading"><?php echo $this->escape($archive['title']); ?></h4>
			<p><?php echo $archive['message']; ?></p>
		</div>
	</div>
	<div class="btn-toolbar">
		<div class="btn-group">
			<a class="btn btn-primary" title="<?php echo $this->escape($archive['date-prev-month']); ?>" href="<?php echo $this->escape($archive['url-prev-month']); ?>"><?php echo $this->escape($archive['date-prev-month']); ?></a>
			<a class="btn btn-info" title="<?php echo $this->escape($archive['date-this-month']); ?>"><?php echo $this->escape($archive['date-this-month']); ?></a>
			<a class="btn btn-primary" title="<?php echo $this->escape($archive['date-next-month']); ?>" href="<?php echo $this->escape($archive['url-next-month']); ?>"><?php echo $this->escape($archive['date-next-month']); ?></a>
		</div>
		<div class="btn-group">
			<a class="btn btn-primary" title="<?php echo $this->escape($archive['date-prev-year']); ?>" href="<?php echo $this->escape($archive['url-prev-year']); ?>"><?php echo $this->escape($archive['date-prev-year']); ?></a>
			<a class="btn btn-info" title="<?php echo $this->escape($archive['date-this-year']); ?>"><?php echo $this->escape($archive['date-this-year']); ?></a>
			<a class="btn btn-primary" title="<?php echo $this->escape($archive['date-next-year']); ?>" href="<?php echo $this->escape($archive['url-next-year']); ?>"><?php echo $this->escape($archive['date-next-year']); ?></a>
		</div>
	</div>
</div>
<?php } ?>