<?php if(isset($attach['audio']) && !empty($attach['audio'])) { ?>
<div class="clearfix">
	<?php 
		$this->jQuery();
		$this->js($this->assetModule('player/audiojs/audio.min.js'));
		$this->footScript()->appendScript("audiojs.events.ready(function(){var as = audiojs.createAll();});");
	?>
	<div class="attach-audio">
		<?php foreach($attach['audio'] as $audio) { ?>
		<div class="player-media col-md-12">
			<audio src="<?php echo $audio['fileUrl']; ?>" preload="auto" />
		</div>
		<?php } ?>
	</div>
</div>
<?php } ?>