<?php $galleryImages = Pi::api('doc','media')->getGalleryLinkData($story['additional_images'], array(100,320,767,479), null, null, false, array(), 'news', true) ?>
<?php $galleryImagesBig = Pi::api('doc','media')->getGalleryLinkData($story['additional_images'], 'large', null, null, false, array(), 'news') ?>
<?php if ($galleryImages) { ?>
    <div class="clearfix">
        <div class="attach-image">
            <?php foreach($galleryImages as $key => $galleryImage) { ?>
                <div class="col-sm-6 col-md-4">
                    <div class="thumbnail u-photo">
                        <a href="<?php echo $galleryImagesBig[$key]['resized_url']; ?>"
                           title="<?php echo $this->escape($galleryImage['title']); ?><?php if($galleryImage['copyright']) echo ' - ' . $galleryImage['copyright'] ?>">

                            <picture>
                                <source srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-srcset="<?php echo $galleryImage['resized_url'][479]; ?>" media="(max-width: 479px)">
                                <source srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-srcset="<?php echo $galleryImage['resized_url'][767]; ?>" media="(max-width: 767px)">
                                <source srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-srcset="<?php echo $galleryImage['resized_url'][320]; ?>" media="(max-width: 991px)">
                                <source srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-srcset="<?php echo $galleryImage['resized_url'][320]; ?>" media="(max-width: 1199px)">
                                <source srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-srcset="<?php echo $galleryImage['resized_url'][100]; ?>" media="(max-width: 1366px)">
                                <source srcset="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==" data-srcset="<?php echo $galleryImage['resized_url'][100]; ?>" media="(max-width: 2800px)">

                                <img itemprop="image" class="img-responsive lazyload" src="<?php echo $galleryImage['resized_url'][767]; ?>"
                                     alt="<?php echo $this->escape($galleryImage['title']); ?>"/>
                            </picture>
                        </a>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div>
<?php } ?>