<?php if (isset($attach['video']) && !empty($attach['video'])) { ?>
    <div class="clearfix">
        <div class="attach-video">
            <?php foreach ($attach['video'] as $video) { ?>
                <div class="pi-player clearfix">
                    <?php echo $this->videojs($video['fileUrl'], $this->escape($story['largeUrl'])); ?>
                </div>
            <?php } ?>
        </div>
    </div>
<?php } ?>