<?php $galleryImages = Pi::api('doc','media')->getGalleryLinkData($story['additional_images'], 'medium', null, null, false, array(), 'news') ?>
<?php $galleryImagesBig = Pi::api('doc','media')->getGalleryLinkData($story['additional_images'], 'large', null, null, false, array(), 'news') ?>

<?php if ($galleryImages) { ?>
    <div class="clearfix">
        <div class="attach-image">

            <?php foreach($galleryImages as $key => $galleryImage) : ?>
                <div class="col-sm-6 col-md-4">
                    <div class="thumbnail u-photo">
                        <a href="<?php echo $galleryImagesBig[$key]['resized_url']; ?>"
                           title="<?php echo $this->escape($galleryImage['title']); ?>">
                            <img itemprop="image" src="<?php echo $galleryImage['resized_url']; ?>"
                                 alt="<?php echo $this->escape($galleryImage['title']); ?>"/>
                        </a>
                    </div>
                </div>
            <?php endforeach; ?>
        </div>
    </div>
<?php } ?>