<?php if (isset($extra['file']) && !empty($extra['file'])) { ?>
    <div class="clearfix">
        <div class="extra-file">
            <h4><?php _e('Extra links'); ?></h4>
            <?php foreach ($extra['file'] as $field) { ?>
                <?php if (!empty($field['data'])) { ?>
                    <p class="text-center"><a rel="external" target="_blank" class="btn btn-primary"
                                              title="<?php echo $field['title']; ?>"
                                              href="<?php echo $field['data']; ?>"><i
                                    class="fa fa-cloud-download"></i> <?php echo $field['title']; ?></a></p>
                <?php } ?>
            <?php } ?>
        </div>
    </div>
<?php } ?>