<?php $this->css($this->assetModule('css/front.css'), array('defer' => 'defer')); ?>
<div class="clearfix">
    <?php include $this->template('front/feed'); ?>
    <?php include $this->template('front/advertisement'); ?>
    <div class="page-header">
        <h1><?php _e('Author list'); ?></h1>
    </div>
    <?php if (isset($authors) && !empty($authors)) { ?>
        <div class="authorList clearfix" itemscope itemtype="https://schema.org/Person">
            <ul class="list-group">
                <?php foreach ($authors as $author) { ?>
                    <li class="list-group-item col-md-3">
                        <img itemprop="image" src="<?php echo $this->escape($author['thumbUrl']); ?>"
                             alt="<?php echo $this->escape($author['title']); ?>"/>
                        <a itemprop="url" title="<?php echo $this->escape($author['title']); ?>"
                           href="<?php echo $this->escape($author['authorUrl']); ?>">
                            <span itemprop="name"><?php echo $this->escape($author['title']); ?></span>
                        </a>
                    </li>
                <?php } ?>
            </ul>
        </div>
    <?php } else { ?>
        <div class="alert alert-warning" role="alert">
            <?php _e('No author information has been added on this part yet. please check this page later'); ?>
        </div>
    <?php } ?>
</div>