<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="news">
<?php if (isset($authors) && !empty($authors)) { ?>
<div class="tagList clearfix">
	<div class="page-header">
		<h4><?php _e('Author list'); ?></h4>
	</div>
	<div class="row">
		<?php foreach($authors as $author) { ?>
		<div class="col-md-3">
			<div class="well well-small">
				<a title="<?php echo $this->escape($author['title']); ?>" href="<?php echo $this->escape($author['authorUrl']); ?>">
					<?php echo $this->escape($author['title']); ?>
				</a>
			</div>
		</div>
		<?php } ?>
   </div>
</div>
<div class="clearfix"></div>
<?php } ?>
</div>