<?php 
$this->css($this->assetModule('css/front.css'));
	// Image lightbox
	if($config['image_lightbox']){ 
        $script =<<<'EOT'
        $('.gallery').each(function() {
    		$(this).magnificPopup({
        		delegate: 'a',
        		type: 'image',
        		gallery: {
          			enabled:true
        		}
    		});
		});
EOT;
		$this->jQuery(array(
			'extension/jquery.magnific-popup.min.js',
			'extension/magnific-popup.css',
		));
		$this->footScript()->appendScript($script);
	}
?>
<div class="clearfix">
	<?php include $this->template('front/feed'); ?>
    <?php include $this->template('front/topic'); ?>
    <?php include $this->template('front/advertisement'); ?>
    <div class="panel panel-default">
        <div class="panel-heading">
            <h1 class="panel-title"><?php echo $this->escape($author['title']); ?></h1>
        </div>
        <div class="panel-body">
			<div class="pull-left gallery itemImageList">
		   		<?php if($config['image_lightbox']){ ?>
				<a href="<?php echo $this->escape($author['mediumUrl']); ?>" title="<?php echo $this->escape($author['title']); ?>">
					<img class="img-thumbnail" src="<?php echo $this->escape($author['thumbUrl']); ?>" alt="<?php echo $this->escape($author['title']); ?>" />
				</a>
				<?php } else { ?>
				<img class="img-thumbnail" src="<?php echo $this->escape($author['thumbUrl']); ?>" alt="<?php echo $this->escape($author['title']); ?>" />
				<?php } ?>
			</div>
			<?php echo $author['description']; ?>
			<div class="clearfix"></div>
        </div>
    </div>
	<div class="index-list-author">
		<div class="news-role">
			<?php foreach($roles as $role) { ?>
			<?php if (!empty($stores[$role['id']])) { ?>
			<h4><?php echo $this->escape($role['title']); ?></h4>
			<div class="list-group">
			<?php foreach($stores[$role['id']] as $story) { ?>
				<a class="list-group-item <?php echo $topic['column_class']; ?>" title="<?php echo $this->escape($story['title']); ?>" href="<?php echo $this->escape($story['storyUrl']); ?>">
					<?php if ($story['image']) { ?>
					<img src="<?php echo $this->escape($story['thumbUrl']); ?>" alt="<?php echo $this->escape($story['title']); ?>" />
					<?php } ?>
					<?php echo $this->escape($story['title']); ?>
				</a>
            <?php } ?>
            <?php } ?>
			</div>
            <div class="clearfix"></div>
			<?php } ?>
		</div>
	</div>
	<div class="clearfix"></div>
</div>