<?php if(!empty($story['authors']) && $config['show_author']) { ?>
    <div class="pull-left authorStory">
        <?php foreach($story['authors'] as $author) { ?>
            <span itemscope itemtype="http://schema.org/Person">
                <?php echo $author['authorRole']; ?> :
		            <a itemprop="url" title="<?php echo $author['authorName']; ?>" href="<?php echo $author['authorUrl']; ?>">
                        <img itemprop="image" src="<?php echo $author['authorThumbUrl']; ?>" alt="<?php echo $author['authorName']; ?>">
                        <span itemprop="name"><?php echo $author['authorName']; ?></span>
                    </a>
            </span>
        <?php } ?>
    </div>
<?php } ?>
