<?php
$this->css($this->assetModule('css/front.css'), ['defer' => 'defer']);
// Image lightbox
if ($config['image_lightbox']) {
    $script
        = <<<'EOT'
window.addEventListener('DOMContentLoaded', function() {
    $('.gallery').each(function() {
        $(this).magnificPopup({
            delegate: 'a',
            type: 'image',
            gallery: {
                enabled:true
            }
        });
    });
});
EOT;
    $this->jQuery(['extension/jquery.magnific-popup.min.js' => ['defer' => 'defer']]);
    $this->jQuery('extension/magnific-popup.min.css', ['defer' => 'defer']);
    $this->footScript()->appendScript($script);
}

// Set Open Graph tags for meta
$this->doctype('HTML5');
$this->headMeta($author['title'], 'og:title', 'property');
$this->headMeta($this->escape($author['authorUrl']), 'og:url', 'property');
if (isset($author['text_description']) && !empty($author['text_description'])) {
    $this->headMeta(_strip($author['text_description']), 'og:description', 'property');
}
if (!empty($author['largeUrl'])) {
    $this->headMeta($this->escape($author['largeUrl']), 'og:image', 'property');
}
// Set twitter for meta
$this->headMeta($author['title'], 'twitter:title');
if (isset($author['text_description']) && !empty($author['text_description'])) {
    $this->headMeta(_strip($author['text_description']), 'twitter:description');
}
if (!empty($author['largeUrl'])) {
    $this->headMeta($this->escape($author['largeUrl']), 'twitter:image');
}
?>
<div class="clearfix author-info" itemscope itemtype="https://schema.org/Person">
    <?php include $this->template('front/feed'); ?>
    <?php include $this->template('front/topic'); ?>
    <?php include $this->template('front/advertisement'); ?>
    <div class="h-entry">
        <div class="page-header">
            <h1 class="p-name" itemprop="name">
                <?php echo $this->escape($author['title']); ?>
            </h1>
        </div>
        <div class="clearfix">
            <div class="col-md-3 col-sm-4 col-12 gallery itemImageList">
                <?php if ($config['image_lightbox']) { ?>
                    <a href="<?php echo $this->escape($author['mediumUrl']); ?>"
                       title="<?php echo $this->escape($author['title']); ?>">
                        <img itemprop="image" class="img-thumbnail u-photo"
                             src="<?php echo $this->escape($author['thumbUrl']); ?>"
                             alt="<?php echo $this->escape($author['title']); ?>"/>
                    </a>
                <?php } else { ?>
                    <img itemprop="image" class="img-thumbnail u-photo"
                         src="<?php echo $this->escape($author['thumbUrl']); ?>"
                         alt="<?php echo $this->escape($author['title']); ?>"/>
                <?php } ?>
            </div>
            <div class="p-summary col-md-9 col-sm-8 col-12">
                <div itemprop="description clearfix">
                    <?php echo $author['text_description']; ?>
                </div>
                <div class="clearfix socialSharing">
                    <?php echo $this->socialSharing(
                        $config['social_sharing'],
                        $this->escape($author['title']),
                        $this->escape($author['storyUrl']),
                        $this->escape($author['largeUrl'])
                    ); ?>
                </div>
            </div>
        </div>
    </div>
    <div class="index-list-author clearfix" itemtype="https://schema.org/ItemList">
        <div class="news-role">
            <?php foreach ($roles as $role) { ?>
                <div class="clearfix">
                    <?php if (!empty($stores[$role['id']])) { ?>
                        <h4><?php echo $this->escape($role['title']); ?></h4>
                        <div class="list-group">
                            <?php foreach ($stores[$role['id']] as $story) { ?>
                                <a itemscope itemtype="https://schema.org/Article" class="list-group-item col-md-4 col-sm-4 col-12"
                                   title="<?php echo $this->escape($story['title']); ?>"
                                   href="<?php echo $this->escape($story['storyUrl']); ?>">
                                    <?php if ($story['main_image']) { ?>
                                        <img class="col-md-4 col-sm-4 col-4" itemprop="image"
                                             src="<?php echo Pi::api('doc', 'media')->getSingleLinkUrl($story['main_image'])->setConfigModule('news')->thumb(
                                                 'medium'
                                             ); ?>"
                                             alt="<?php echo $this->escape($story['title']); ?>"/>
                                    <?php } ?>
                                    <span itemprop="name headline" class="col-md-8 col-sm-8 col-8"><?php echo $this->escape($story['title']); ?></span>
                                    <meta itemprop="datePublished" content="<?php echo $this->escape(date("Y-m-d H:i:s", $story['time_publish'])); ?>"/>
                                </a>
                            <?php } ?>
                        </div>
                    <?php } ?>
                </div>
            <?php } ?>
        </div>
    </div>
</div>