<?php if (isset($authors) && !empty($authors)) { ?>
    <div class="clearfix">
        <div class="authorList clearfix" itemscope itemtype="https://schema.org/Person">
            <?php foreach ($authors as $author) { ?>
                <div class="media">
                    <div class="col-md-3 media-left">
                        <img itemprop="image" class="media-object img-responsive img-circle" src="<?php echo $this->escape($author['thumbUrl']); ?>"
                             alt="<?php echo $this->escape($author['title']); ?>">
                    </div>
                    <div class="col-md-9 media-body">
                        <h4 class="media-heading">
                            <a itemprop="url" title="<?php echo $this->escape($author['title']); ?>"
                               href="<?php echo $this->escape($author['authorUrl']); ?>">
                                <span itemprop="name"><?php echo $this->escape($author['title']); ?></span>
                            </a>
                        </h4>
                        <div itemprop="description" class="clearfix">
                            <?php echo $author['text_description']; ?>
                        </div>
                    </div>
                </div>
            <?php } ?>
        </div>
    </div>
<?php } ?>


