<?php if(isset($extra['all']) && !empty($extra['all'])) { ?>
<div class="storyInfoBox well clearfix">
	<div class="storyExtra">
	<?php foreach($extra['all'] as $field) { ?>
		<?php if(!empty($field['data'])) { ?>
		<div class="field-<?php echo $field['id']; ?>">
			<?php if($field['image']) { ?>
			<img src="<?php echo $field['imageUrl']; ?>" alt="<?php echo $field['title']; ?>" />
			<?php } ?>
			<?php if($field['type'] == 'text' || $field['type'] == 'select') { ?>
			<strong><?php echo $field['title']; ?></strong>
			<span><?php echo $field['data']; ?></span>
			<?php } elseif($field['type'] == 'link') { ?>
			<span><a title="<?php echo $field['title']; ?>" href="<?php echo $field['data']; ?>"><?php echo $field['title']; ?></a></span>
			<?php } elseif($field['type'] == 'file') { ?>
			<span><a title="<?php echo $field['title']; ?>" href="<?php echo $field['data']; ?>"><?php echo $field['title']; ?></a></span>
			<?php } elseif($field['type'] == 'currency') { ?>
			<strong><?php echo $field['title']; ?></strong>
			<span><?php echo $this->currencyFormat($field['data'], "USD", "en_US"); ?></span>
			<?php } elseif($field['type'] == 'date') { ?>
			<strong><?php echo $field['title']; ?></strong>
			<span><?php echo $this->dateFormat($field['data'], IntlDateFormatter::MEDIUM, IntlDateFormatter::MEDIUM, "en_US"); ?></span>
			<?php } elseif($field['type'] == 'number') { ?>
			<strong><?php echo $field['title']; ?></strong>
			<span><?php echo $this->numberFormat($field['data'], NumberFormatter::PATTERN_DECIMAL, NumberFormatter::TYPE_DEFAULT, "en_US"); ?></span>
			<?php } ?>
		</div>
		<?php } ?>
	<?php } ?>
	</div>
</div>
<?php } ?>