<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="news">
  <?php include $this->template('front/topicinfo'); ?>
  <?php include $this->template('front/spotlight'); ?>
  <?php if(!empty($config['advertisement'])){ ?><div class="itemAds"><?php echo $config['advertisement']; ?></div><?php } ?>
	<div class="typelist itemList">
		<ul>
		<?php foreach($stores as $story) { ?>
			<li class="<?php echo $topic['column_class']; ?>"><?php if($story['important']) { ?><span class="label label-important"><?php _e('Important'); ?></span><?php } ?><a title="<?php echo $this->escape($story['title']); ?>" href="<?php echo $this->url('.news', array('module' => $module ,'controller' => 'story' ,'alias' => $this->escape($story['alias']))); ?>"><?php echo $this->escape($story['title']); ?></a></li>
		<?php } ?>
		</ul>
		<div class="clearfix"></div>
	</div>
   <div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator'); ?></div>
</div>