<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="news">
   <?php include $this->template('front/topicinfo'); ?>
   <?php include $this->template('front/spotlight'); ?>
   <?php if(!empty($config['advertisement'])){ ?><div class="itemAds"><?php echo $config['advertisement']; ?></div><?php } ?>
	<div class="typetable">
		<table class="table table-striped table-bordered table-condensed">
			<tr>
				<th><?php _e('Title'); ?></th>
				<?php if($topic['showdate']){ ?><th><?php _e('Update Time'); ?></th><?php } ?>
				<?php if($topic['showhits']){ ?><th><?php _e('Read'); ?></th><?php } ?>
			</tr>
			<?php foreach($stores as $story) { ?>
			<tr>
				<td><?php if($story['important']) { ?><span class="label label-important"><?php _e('Important'); ?></span><?php } ?><a title="<?php echo $this->escape($story['title']); ?>" href="<?php echo $this->url('.news', array('module' => $module ,'controller' => 'story' ,'alias' => $this->escape($story['alias']))); ?>"><?php echo $this->escape($story['title']); ?></a></td>
				<?php if($topic['showdate']){ ?><td><?php echo $this->escape($story['publish']); ?></td><?php } ?>
				<?php if($topic['showhits']){ ?><td><?php echo $this->escape($story['hits']); ?></td><?php } ?>
			</tr>
			<?php } ?>
		</table>
		<div class="clearfix"></div>
	</div>
   <div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator'); ?></div>
</div>