<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="news">
	<?php include $this->template('front/feed'); ?>
    <?php include $this->template('front/topicinfo'); ?>
    <?php include $this->template('front/spotlight'); ?>
    <?php include $this->template('front/advertisement'); ?>
	<div class="typelist itemList">
		<ul>
		<?php foreach($stores as $story) { ?>
			<li class="<?php echo $topic['column_class']; ?>"><?php if($story['important']) { ?><span class="label label-important"><?php _e('Important'); ?></span><?php } ?><a title="<?php echo $this->escape($story['title']); ?>" href="<?php echo $this->url('.news', array('module' => $module ,'controller' => 'story' ,'slug' => $this->escape($story['slug']))); ?>"><?php echo $this->escape($story['title']); ?></a></li>
		<?php } ?>
		</ul>
		<div class="clearfix"></div>
	</div>
   <div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator'); ?></div>
</div>