<?php $this->css($this->assetModule('css/front.css'), ['defer' => 'defer']); ?>
<div class="clearfix">
    <?php include $this->template('front/feed'); ?>
    <?php include $this->template('front/topic'); ?>
    <?php include $this->template('front/spotlight'); ?>
    <div class="index-list clearfix row">
        <?php foreach ($stores as $story) { ?>
            <div class="<?php echo $topic['column_class']; ?>">
                <div class="card mb-3 h-entry clearfix" itemscope itemtype="https://schema.org/Article">
                    <div class="row no-gutters">
                        <div class="col-md-4 col-3 u-photo">
                            <?php if ($story['main_image']) { ?>
                                <img itemprop="image" class="card-img" src="<?php echo $this->escape($story['thumbUrl']); ?>" alt="<?php echo $this->escape($story['title']); ?>"/>
                            <?php } ?>
                        </div>
                        <div class="col-md-8 col-9">
                            <div class="card-body p-3">
                                <h2 itemprop="card-title name headline">
                                    <a class="p-name" itemprop="url" title="<?php echo $this->escape($story['title']); ?>" href="<?php echo $this->escape($story['storyUrl']); ?>">
                                        <?php echo $this->escape($story['title']); ?>
                                    </a>
                                </h2>
                                <div class="card-text mt-3">
                                    <?php if ($topic['show_topic']) { ?>
                                        <div class="clearfix small"> <?php _e('Topics'); ?> :
                                            <?php foreach ($story['topics'] as $storyTopic) { ?>
                                                <a class="p-category" itemprop="about" title="<?php echo $storyTopic['title']; ?>" href="<?php echo $storyTopic['url']; ?>">
                                                    <?php echo $storyTopic['title']; ?>
                                                </a>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>
                                    <?php if (!empty($story['authors'])) { ?>
                                        <div class="clearfix small">
                                            <?php foreach ($story['authors'] as $author) { ?>
                                                <span class="p-author" itemprop="publisher"><?php echo $author['authorRole']; ?> :
                                                <a title="<?php echo $author['authorName']; ?>" href="<?php echo $author['authorUrl']; ?>">
                                                    <?php echo $author['authorName']; ?>
                                                </a>
                                            </span>
                                            <?php } ?>
                                        </div>
                                    <?php } ?>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <meta itemprop="datePublished" content="<?php echo $this->escape(date("Y-m-d H:i:s", $story['time_publish'])); ?>"/>
        <?php } ?>
    </div>
    <div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?></div>
</div>