<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="news">
    <?php include $this->template('front/feed'); ?>
    <?php include $this->template('front/archive'); ?>
    <?php include $this->template('front/topic'); ?>
    <?php include $this->template('front/writer'); ?>
    <?php include $this->template('front/spotlight'); ?>
    <?php include $this->template('front/advertisement'); ?>
	<div class="index-news">
	    <?php foreach($stores as $story) { ?>
		<?php if ($topic['column_class']) { ?><div class="<?php echo $topic['column_class']; ?>"><?php } ?>
			<div class="panel panel-default">
  				<div class="panel-heading">
  					<h3 class="panel-title"><?php if($story['important']) { ?><span class="label label-danger"><?php _e('Important'); ?></span><?php } ?><a title="<?php echo $story['title']; ?>" href="<?php echo $story['storyUrl']; ?>"><?php echo $this->escape($story['title']); ?></a></h3>
  				</div>
				<div class="panel-body">
					<?php if($story['image']){ ?>
					<div class="col-md-3">
						<div class="thumbnail">
							<a href="<?php echo $story['storyUrl']; ?>" title="<?php echo $this->escape($story['title']); ?>"><img src="<?php echo $story['mediumUrl']; ?>" alt="<?php echo $this->escape($story['title']); ?>" /></a>
						</div>
					</div>
		    		<?php } ?>
			   	   	<div class="text-justify"><?php echo $story['short']; ?></div>
			   	   	<div class="clearfix">
						<div class="pull-right">
						<?php if($topic['show_date']){ ?>
						<span class="itemPostDate">
							<?php _e('Time'); ?>: <?php echo $this->escape($story['time_publish_view']); ?>
						</span>
						<?php } ?>
						<?php if($topic['show_hits']){ ?>
						<span class="itemStats">
							<?php _e('Read'); ?>: <?php echo _number($this->escape($story['hits'])); ?> <?php _e('Times'); ?>
						</span>
						<?php } ?>
						</div>
						<?php if($topic['show_topic']) { ?>
						<div class="pull-left"><?php _e('Topics'); ?> : 
						<?php foreach($story['topics'] as $storyTopic) { ?>
							<a title="<?php echo $storyTopic['title']; ?>" href="<?php echo $storyTopic['url']; ?>"><?php echo $storyTopic['title']; ?></a> , 
						<?php } ?>
						</div>
						<?php } ?>
					</div>
				   	<div class="clearfix"></div>
				</div>
			</div>
		<?php if ($topic['column_class']) { ?></div><?php } ?>
	    <?php } ?>
	    <div class="clearfix"></div>
	</div>
    <div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?></div>
</div>