<?php
$this->css($this->assetModule('css/front.css'));
// Set robots nofollow
if (isset($searchResult) && $searchResult) {
    $this->headMeta('noindex', 'robots');
}
?>
<div class="clearfix">
    <?php include $this->template('front/feed'); ?>
    <?php include $this->template('front/topic'); ?>
    <?php include $this->template('front/spotlight'); ?>
    <?php include $this->template('front/advertisement'); ?>
    <div class="index-list">
        <ul class="list-group">
            <?php foreach ($stores as $story) { ?>
                <li class="list-group-item <?php echo $topic['column_class']; ?> h-entry clearfix" itemscope
                    itemtype="http://schema.org/Article">
                    <div class="col-xs-3">
                        <?php if ($story['image']) { ?>
                            <span class="u-photo">
		    		        <img itemprop="image" src="<?php echo $this->escape($story['thumbUrl']); ?>"
                                 alt="<?php echo $this->escape($story['title']); ?>"/>
		    	        </span>
                        <?php } ?>
                    </div>
                    <div class="col-xs-9">
                        <h2 itemprop="name headline">
                            <a class="p-name" itemprop="url" title="<?php echo $this->escape($story['title']); ?>"
                               href="<?php echo $this->escape($story['storyUrl']); ?>"><?php echo $this->escape($story['title']); ?></a>
                        </h2>
                        <?php if ($topic['show_topic']) { ?>
                            <div class="clearfix small"> <?php _e('Topics'); ?> :
                                <?php foreach ($story['topics'] as $storyTopic) { ?>
                                    <span class=" p-category" itemprop="about"><a
                                            title="<?php echo $storyTopic['title']; ?>"
                                            href="<?php echo $storyTopic['url']; ?>"><?php echo $storyTopic['title']; ?></a></span>
                                <?php } ?>
                            </div>
                        <?php } ?>
                        <?php if (!empty($story['authors'])) { ?>
                            <div class="clearfix small">
                                <?php foreach ($story['authors'] as $author) { ?>
                                    <span class="p-author" itemprop="publisher"><?php echo $author['authorRole']; ?> : <a
                                            title="<?php echo $author['authorName']; ?>"
                                            href="<?php echo $author['authorUrl']; ?>"><?php echo $author['authorName']; ?></a></span>
                                <?php } ?>
                            </div>
                        <?php } ?>
                    </div>
                    <meta itemprop="datePublished" content="<?php echo $this->escape(date("Y-m-d H:i:s", $story['time_publish'])); ?>" />
                </li>
            <?php } ?>
        </ul>
        <div class="clearfix"></div>
    </div>
    <div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?></div>
</div>