<?php $this->css($this->assetModule('css/front.css'), array('defer' => 'defer')); ?>
<div class="clearfix">
    <?php include $this->template('front/feed'); ?>
    <?php include $this->template('front/topic'); ?>
    <?php include $this->template('front/spotlight'); ?>
    <?php include $this->template('front/advertisement'); ?>
    <div class="index-news clearfix">
        <?php foreach ($stores as $story) { ?>
            <?php if ($topic['column_class']) { ?><div class="<?php echo $topic['column_class']; ?>"><?php } ?>
            <div class="single-news h-entry clearfix" itemscope itemtype="https://schema.org/Article">
                <div class="single-news-heading">
                    <h3 class="p-name" itemprop="name headline">
                        <?php if ($story['important']) { ?><span class="label label-danger"><?php _e('Important'); ?></span><?php } ?>
                        <a itemprop="url" title="<?php echo $story['title']; ?>" href="<?php echo $story['storyUrl']; ?>">
                            <?php echo $this->escape($story['title']); ?>
                        </a>
                    </h3>
                </div>
                <div class="single-news-body">
                    <div class="clearfix">
                        <?php if ($story['main_image']) { ?>
                            <div class="col-md-3 u-photo">
                                <a itemprop="url" href="<?php echo $story['storyUrl']; ?>"
                                   title="<?php echo $this->escape($story['title']); ?>">
                                    <img class="img-responsive img-thumbnail" itemprop="image" src="<?php echo Pi::api('doc','media')->getSingleLinkUrl($story['main_image'])->setConfigModule('news')->thumb('medium'); ?>"
                                         alt="<?php echo $this->escape($story['title']); ?>"/>
                                </a>
                            </div>
                        <?php } ?>
                        <div class="storyText p-summary" itemprop="description">
                            <?php echo $story['text_summary']; ?>
                        </div>
                    </div>
                    <div class="clearfix">
                        <ul class="list-inline small">
                            <?php if ($topic['show_date']) { ?>
                                <li class="itemPostDate dt-published" itemprop="datePublished">
                                    <?php _e('Time'); ?> : <?php echo $this->escape($story['time_publish_view']); ?>
                                </li>
                            <?php } ?>
                            <?php if ($topic['show_hits']) { ?>
                                <li class="itemStats">
                                    <?php _e('Read'); ?> : <?php echo _number($this->escape($story['hits'])); ?> <?php _e('Times'); ?>
                                </li>
                            <?php } ?>
                            <?php if ($topic['show_topic']) { ?>
                                <li>
                                    <?php _e('Topics'); ?> : <?php foreach ($story['topics'] as $storyTopic) { ?>
                                        <span class=" p-category" itemprop="about"><a
                                                title="<?php echo $storyTopic['title']; ?>"
                                                href="<?php echo $storyTopic['url']; ?>"><?php echo $storyTopic['title']; ?></a></span>
                                    <?php } ?>
                                </li>
                            <?php } ?>
                            <?php if (!empty($story['authors'])) { ?>
                                <li>
                                    <?php foreach ($story['authors'] as $author) { ?>
                                        <span class="p-author" itemprop="publisher"><?php echo $author['authorRole']; ?>
                                            : <a title="<?php echo $author['authorName']; ?>"
                                                 href="<?php echo $author['authorUrl']; ?>"><?php echo $author['authorName']; ?></a></span>
                                    <?php } ?>
                                </li>
                            <?php } ?>
                        </ul>
                    </div>
                </div>
                <meta itemprop="datePublished" content="<?php echo $this->escape(date("Y-m-d H:i:s", $story['time_publish'])); ?>" />
            </div>
            <?php if ($topic['column_class']) { ?></div><?php } ?>
        <?php } ?>
    </div>
    <div class="paginator">
        <?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?>
    </div>
</div>