<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="news">
    <?php include $this->template('front/feed'); ?>
    <?php include $this->template('front/archive'); ?>
    <?php include $this->template('front/topic'); ?>
    <?php include $this->template('front/writer'); ?>
    <?php include $this->template('front/spotlight'); ?>
    <?php include $this->template('front/advertisement'); ?>
	<div class="index-table">
		<table class="table table-striped table-bordered table-condensed">
			<tr>
				<th><?php _e('Title'); ?></th>
				<?php if($topic['showdate']){ ?><th><?php _e('Update Time'); ?></th><?php } ?>
				<?php if($topic['showhits']){ ?><th><?php _e('Read'); ?></th><?php } ?>
			</tr>
			<?php foreach($stores as $story) { ?>
			<tr>
				<td><?php if($story['important']) { ?><span class="label label-danger"><?php _e('Important'); ?></span><?php } ?><a title="<?php echo $story['title']; ?>" href="<?php echo $story['storyUrl']; ?>"><?php echo $this->escape($story['title']); ?></a><</td>
				<?php if($topic['showdate']){ ?><td><?php echo $this->escape($story['time_publish']); ?></td><?php } ?>
				<?php if($topic['showhits']){ ?><td><?php echo $this->escape($story['hits']); ?></td><?php } ?>
			</tr>
			<?php } ?>
		</table>
	    <div class="clearfix"></div>
	</div>
    <div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?></div>
</div>