<?php $this->css($this->assetModule('css/front.css'), ['defer' => 'defer']); ?>
<div class="clearfix">
    <?php include $this->template('front/feed'); ?>
    <?php include $this->template('front/topic'); ?>
    <?php include $this->template('front/spotlight'); ?>
    <?php include $this->template('front/advertisement'); ?>
    <div class="index-topic match-height-list">
        <?php foreach ($topics as $topic) { ?>
            <div class="col-xs-12 col-md-2 col-sm-2 col-xs-3 text-center" itemscope itemtype="https://schema.org/Article">
                <div class="thumbnail h-entry">
                    <?php if ($topic['main_image']) { ?>
                        <a itemprop="url" title="<?php echo $this->escape($topic['title']); ?>"
                           href="<?php echo $this->escape($topic['topicUrl']); ?>">
                            <img itemprop="image" src="<?php echo $this->escape($topic['thumbUrl']); ?>"
                                 alt="<?php echo $this->escape($topic['title']); ?>"/>
                        </a>
                    <?php } ?>
                    <div class="caption">
                        <h5 class="p-name" itemprop="name">
                            <a itemprop="url" title="<?php echo $this->escape($topic['title']); ?>"
                               href="<?php echo $this->escape($topic['topicUrl']); ?>"><?php echo $this->escape($topic['title']); ?></a>
                        </h5>
                    </div>
                </div>
                <div class="clearfix"></div>
            </div>
        <?php } ?>
        <div class="clearfix"></div>
    </div>
</div>