<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="news">
    <?php include $this->template('front/feed'); ?>
    <?php include $this->template('front/archive'); ?>
    <?php include $this->template('front/topic'); ?>
    <?php include $this->template('front/writer'); ?>
    <?php include $this->template('front/spotlight'); ?>
    <?php include $this->template('front/advertisement'); ?>
	<div class="index-topic">
	    <?php foreach($topics as $topic) { ?>
		<?php if ($topic['column_class']) { ?><div class="<?php echo $topic['column_class']; ?>"><?php } ?>
		<div class="thumbnail">
			<?php if($topic['image']){ ?>
			<a title="<?php echo $this->escape($topic['title']); ?>" href="<?php echo $this->escape($topic['topicUrl']); ?>">
				<img class="img-thumbnail pull-right" src="<?php echo $this->escape($topic['thumbUrl']); ?>" alt="<?php echo $this->escape($topic['title']); ?>" />
			</a>
			<?php } ?>
			<div class="caption">
				<h5>
					<a title="<?php echo $this->escape($topic['title']); ?>" href="<?php echo $this->escape($topic['topicUrl']); ?>"><?php echo $this->escape($topic['title']); ?></a>
				</h5>
			</div>
		</div>
	    <?php if ($topic['column_class']) { ?></div><?php } ?>
	    <?php } ?>
	    <div class="clearfix"></div>
	</div>
    <div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?></div>
</div>