<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="news">
    <?php include $this->template('front/feed'); ?>
    <?php include $this->template('front/archive'); ?>
    <?php include $this->template('front/topic'); ?>
    <?php include $this->template('front/writer'); ?>
    <?php include $this->template('front/spotlight'); ?>
    <?php include $this->template('front/advertisement'); ?>
	<div class="index-media">
	    <?php foreach($stores as $story) { ?>
		<div class="<?php echo $topic['column_class']; ?>">
		<div class="item">
			<?php if($story['image']){ ?>
			<div class="itemImageList gallery">
				<a title="<?php echo $story['title']; ?>" href="<?php echo $story['storyUrl']; ?>"><img class="img-thumbnail ItemStoryImg" src="<?php echo $story['thumbUrl']; ?>" alt="<?php echo $this->escape($story['title']); ?>" /></a>
		    </div>
			<div class="clearfix"></div>
		    <?php } ?>
			<div class="itemTitle">
				<h3><?php if($story['important']) { ?><span class="label label-danger"><?php _e('Important'); ?></span><?php } ?><a title="<?php echo $story['title']; ?>" href="<?php echo $story['storyUrl']; ?>"><?php echo $this->escape($story['title']); ?></a></h3>
			</div>
		</div>
		</div>
	    <?php } ?>
	    <div class="clearfix"></div>
	</div>
    <div class="paginator"><?php echo $this->paginationControl($paginator, 'Sliding', 'paginator.phtml'); ?></div>
</div>