<?php
    $this->css(array(
        $this->assetModule('css/front.css'),
        $this->assetModule('script/system-ui.css', 'system'),
    ));
    $this->jQuery();
    $this->js(array(
        $this->assetModule('script/cache.js', 'system'),
        $this->assetModule('script/tip-alert.js', 'system'),
    ));
?>
<div class="news">
	<h2><?php echo $this->escape($title); ?></h2>
	<div id="story-form">
	<?php include $this->templateComponent('form'); ?>
	</div>
</div> 
<script type="text/javascript" >
(function($){
    $("#story-form").on("click","button",function(){
       beautAlert.done("<?php _e('Remove image story in process'); ?>","wait");
       $.getJSON($(this).attr("data-link")).done(function(result){
          if(result.status==1){
             beautAlert.done(result.message,"succ");
          }else{
             beautAlert.done(result.message,"fail");
          }
       });
    });
})(jQuery)
</script>