<?php $this->css($this->assetModule('css/front.css'), array('defer' => 'defer')); ?>
<div class="clearfix">
    <div class="media">
        <div class="col-md-2">
            <div class="text-center">
                <a href="<?php echo $microblog['profileUrl']; ?>" title="<?php echo $microblog['user']['name']; ?>">
                    <?php echo $microblog['user']['avatar']; ?>
                </a>
            </div>
        </div>
        <div class="media-body col-md-10">
            <div class="clearfix">
                <ul class="list-inline">
                    <li>
                        <a href="<?php echo $microblog['profileUrl']; ?>" title="<?php echo $microblog['user']['name']; ?>">
                            <?php echo $microblog['user']['name']; ?>
                        </a>
                    </li>
                    <li>
                        <a href="<?php echo $microblog['microblogUrl']; ?>" title="<?php echo $microblog['seo_title']; ?>">
                            <?php echo $microblog['time_create_view']; ?>
                        </a>
                    </li>
                </ul>
            </div>
            <div class="clearfix">
                <?php echo $microblog['post']; ?>
            </div>
        </div>
    </div>
</div>