<?php if($config['social_facebook'] || $config['social_twitter'] || $config['social_gplus'] || $config['social_pinterest']) { ?>
<?php 
    // More info : https://github.com/kni-labs/rrssb
	$this->jQuery();
	$this->js($this->assetModule('js/rrssb.min.js'));
    $this->css($this->assetModule('css/rrssb.css'));
?> 
<div class="share-container clearfix">
    <ul class="rrssb-buttons clearfix">
    	<?php if($config['social_facebook']) { ?>
        <li class="facebook">
            <a title="<?php _e('Facebook'); ?>" href="https://www.facebook.com/sharer/sharer.php?u=<?php echo $this->escape($story['storyUrl']); ?>" class="popup">
                <span class="icon"><i class="fa fa-facebook"></i></span>
                <span class="text"><?php _e('Facebook'); ?></span>
            </a>
        </li>
        <?php } ?>
        <?php if($config['social_twitter']) { ?>
        <li class="twitter">
            <a title="<?php _e('Twitter'); ?>" href="http://www.twitter.com/home?status=<?php echo $this->escape($story['title']); ?><?php echo $this->escape($story['storyUrl']); ?>" class="popup">
                <span class="icon"><i class="fa fa-twitter"></i></span>
                <span class="text"><?php _e('Twitter'); ?></span>
            </a>
        </li>
        <?php } ?>
        <?php if($config['social_gplus']) { ?>
        <li class="googleplus">
            <a title="<?php _e('Google +'); ?>" href="https://plus.google.com/share?url=<?php echo $this->escape($story['title']); ?><?php echo $this->escape($story['storyUrl']); ?>" class="popup">
                <span class="icon"><i class="fa fa-google-plus"></i></span>
                <span class="text"><?php _e('Google +'); ?></span>
            </a>
        </li>
        <?php } ?>
        <?php if($config['social_pinterest']) { ?>
        <li class="pinterest">
            <a title="<?php _e('Pinterest'); ?>" href="http://www.pinterest.com/pin/create/button/?url=<?php echo $this->escape($story['storyUrl']); ?>&amp;media=<?php echo $this->escape($story['largeUrl']); ?>&amp;description=<?php echo $this->escape($story['title']); ?>">
                <span class="icon"><i class="fa fa-pinterest"></i></span>
                <span class="text"><?php _e('Pinterest'); ?></span>
            </a>
        </li>
        <?php } ?>
    </ul>
</div>
<?php } ?>