<?php if ($config['show_spotlight'] && isset($spotlight) && !empty($spotlight)) { ?>
<div class="spotlight">
	<div class="row">
	   <?php if(!empty($spotlight['top'])) { ?>
		<div class="spotlightTop col-md-12">
			<div class="spotlightTitle">
				<h2>
					<a title="<?php echo $this->escape($spotlight['top']['title']); ?>" href="<?php echo $this->escape($spotlight['top']['storyUrl']); ?>"><?php echo $this->escape($spotlight['top']['title']); ?></a>
				</h2>
			</div>
			<div class="spotlightBody">
				<?php if($spotlight['top']['image']){ ?>
			    <div class="itemImageList left">
			    	<?php if($config['image_lightbox']){ ?>
					<a href="<?php echo $spotlight['top']['mediumUrl']; ?>" title="<?php echo $this->escape($spotlight['top']['title']); ?>"><img class="left ItemStoryImg img-thumbnail" src="<?php echo $spotlight['top']['thumbUrl']; ?>" alt="<?php echo $this->escape($spotlight['top']['title']); ?>" /></a>
					<?php } else { ?>
					<img class="left ItemStoryImg img-thumbnail" src="<?php echo $spotlight['top']['thumbUrl']; ?>" alt="<?php echo $this->escape($spotlight['top']['title']); ?>" />
					<?php } ?>
				</div>
			    <?php } ?>
				<div class="spotlightText"><?php echo $this->escape($spotlight['top']['text_summary']); ?></div>
				<div class="clearfix"></div>
			</div>
		</div>
		<?php } ?>
		<?php if(!empty($spotlight['list'])) { ?>
		<div class="spotlightList">
			<?php foreach($spotlight['list'] as $story) { ?>
			<div class="spotlightListItem span6">
				<div class="spotlightTitle">
					<h4>
						<a title="<?php echo $story['title']; ?>" href="<?php echo $this->escape($spotlight['top']['storyUrl']); ?>"><?php echo $this->escape($story['title']); ?></a>
					</h4>
				</div>
				<div class="spotlightBody">
					<?php if($story['image'] && $config['spotlight_image']){ ?>
				    <div class="itemImageList left">
						<?php if($config['image_lightbox']){ ?>
						<a href="<?php echo $story['mediumUrl']; ?>" title="<?php echo $this->escape($story['title']); ?>"><img class="left ItemStoryImg img-thumbnail" src="<?php echo $story['thumbUrl']; ?>" alt="<?php echo $this->escape($story['title']); ?>" /></a>
				    	<?php } else { ?>
				    	<img class="left ItemStoryImg img-thumbnail" src="<?php echo $story['thumbUrl']; ?>" alt="<?php echo $this->escape($story['title']); ?>" />
				    	<?php } ?>
				    </div>
					<?php } ?>
					<div class="spotlightText"><?php echo $this->escape($story['text_summary']); ?></div>
					<div class="clearfix"></div>
				</div>
			</div>
			<?php } ?>
			<div class="clearfix"></div>
		</div>
		<?php } ?>
	</div>
</div>
<?php } ?>