<?php 
if(!empty($spotlight)) {
	$this->css($this->assetModule('css/spotlight.css'));
	if($config['image_lightbox']){ 
		$this->jQuery();
		$this->js($this->assetModule('js/lightbox.js'));
		$this->footScript()->appendScript("$(function() {
			$('.gallery a').lightBox({
		        imageLoading: '" . $this->assetModule('image/lightbox-ico-loading.gif') . "',
		        imageBtnClose:'" . $this->assetModule('image/lightbox-btn-close.gif') . "',
		        imageBtnNext:'" . $this->assetModule('image/lightbox-btn-next.gif') . "',
		        imageBtnPrev:'" . $this->assetModule('image/lightbox-btn-prev.gif') . "',
		        imageBlank:'" . $this->assetModule('image/lightbox-blank.gif') . "',
		        overlayOpacity: 0.6,
			    containerResizeSpeed: 350,
			});
		});");
		$this->css($this->assetModule('css/lightbox.css'));
	} 
?>
<div class="spotlight well">
	<div class="row-fluid">
	   <?php if(!empty($spotlight['top'])) { ?>
		<div class="spotlightTop span12">
			<div class="spotlightTitle">
				<h2>
					<a title="<?php echo $this->escape($spotlight['top']['title']); ?>" href="<?php echo $this->url('.news', array('module' => $module ,'controller' => 'story' ,'slug' => $this->escape($spotlight['top']['slug']))); ?>"><?php echo $this->escape($spotlight['top']['title']); ?></a>
				</h2>
			</div>
			<div class="spotlightBody">
				<?php if($spotlight['top']['image']){ ?>
			    <div class="itemImageList gallery <?php echo $config['image_float']; ?>">
			    	<?php if($config['image_lightbox']){ ?>
					<a href="<?php echo $spotlight['top']['mediumurl']; ?>" title="<?php echo $this->escape($spotlight['top']['title']); ?>"><img class="<?php echo $config['image_float']; ?> ItemStoryImg img-polaroid" src="<?php echo $spotlight['top']['thumburl']; ?>" alt="<?php echo $this->escape($spotlight['top']['title']); ?>" /></a>
					<?php } else { ?>
					<img class="<?php echo $config['image_float']; ?> ItemStoryImg img-polaroid" src="<?php echo $spotlight['top']['thumburl']; ?>" alt="<?php echo $this->escape($spotlight['top']['title']); ?>" />
					<?php } ?>
				</div>
			    <?php } ?>
				<div class="spotlightText"><?php echo $this->escape($spotlight['top']['short']); ?></div>
				<div class="clearfix"></div>
			</div>
		</div>
		<?php } ?>
		<?php if(!empty($spotlight['list'])) { ?>
		<div class="spotlightList">
			<?php foreach($spotlight['list'] as $story) { ?>
			<div class="spotlightListItem span6">
				<div class="spotlightTitle">
					<h4>
						<a title="<?php echo $story['title']; ?>" href="<?php echo $this->url('.news', array('module' => $module ,'controller' => 'story' ,'slug' => $this->escape($story['slug']))); ?>"><?php echo $this->escape($story['title']); ?></a>
					</h4>
				</div>
				<div class="spotlightBody">
					<?php if($story['image'] && $config['spotlight_image']){ ?>
				    <div class="itemImageList gallery <?php echo $config['image_float']; ?>">
						<?php if($config['image_lightbox']){ ?>
						<a href="<?php echo $story['mediumurl']; ?>" title="<?php echo $this->escape($story['title']); ?>"><img class="<?php echo $config['image_float']; ?> ItemStoryImg img-polaroid" src="<?php echo $story['thumburl']; ?>" alt="<?php echo $this->escape($story['title']); ?>" /></a>
				    	<?php } else { ?>
				    	<img class="<?php echo $config['image_float']; ?> ItemStoryImg img-polaroid" src="<?php echo $story['thumburl']; ?>" alt="<?php echo $this->escape($story['title']); ?>" />
				    	<?php } ?>
				    </div>
					<?php } ?>
					<div class="spotlightText"><?php echo $this->escape($story['short']); ?></div>
					<div class="clearfix"></div>
				</div>
			</div>
			<?php } ?>
			<div class="clearfix"></div>
		</div>
		<?php } ?>
	</div>
</div>
<?php } ?>