<?php
// Load front.css
$this->css($this->assetModule('css/front.css'), array('defer' => 'defer'));
// Image lightbox
if ($config['image_lightbox']) {
    $script = <<<'EOT'
window.addEventListener('DOMContentLoaded', function() {
    $('.gallery').each(function() {
        $(this).magnificPopup({
            delegate: 'a',
            type: 'image',
            gallery: {
                enabled:true
            }
        });
    });
});
EOT;
    $this->jQuery(array('extension/jquery.magnific-popup.min.js' => array('defer' => 'defer')));
    $this->jQuery('extension/magnific-popup.min.css', array('defer' => 'defer'));
    $this->footScript()->appendScript($script);
}
// Set Open Graph tags for meta
$this->doctype('HTML5');
$shareImage = (string) Pi::api('doc','media')->getSingleLinkUrl($story['main_image'])->setConfigModule('news')->thumb('large');
$this->headMeta($this->escape($story['title']), 'og:title', 'property');
$this->headMeta($this->escape($story['storyUrl']), 'og:url', 'property');
if (isset($story['text_summary']) && !empty($story['text_summary'])) {
    $this->headMeta(_strip($story['text_summary']), 'og:description', 'property');
}
if ($shareImage) {
    $this->headMeta($shareImage, 'og:image', 'property');
}
// Set twitter for meta
$this->headMeta($this->escape($story['title']), 'twitter:title');
if (isset($story['text_summary']) && !empty($story['text_summary'])) {
    $this->headMeta(_strip($story['text_summary']), 'twitter:description');
}
if ($shareImage) {
    $this->headMeta($shareImage, 'twitter:image');
}

$this->js(Pi::url('static/vendor/lazysizes/lazysizes.min.js'), array('async' => 'async'));

?>
<div class="clearfix news-single-story" itemscope itemtype="https://schema.org/Article">
    <?php include $this->template('front/feed'); ?>
    <?php include $this->template('front/advertisement'); ?>

    <div class="clearfix page-header">
        <h1 class="p-name" itemprop="name headline">
            <?php if ($story['important']) { ?>
                <span class="label label-important">
					    <?php _e('Important'); ?>
				    </span>
            <?php } ?>
            <?php echo $this->escape($story['title']); ?>
        </h1>
    </div>

    <meta itemprop="datePublished" content="<?php echo $this->escape(date("Y-m-d H:i:s", $story['time_publish'])); ?>" />
    <div class="clearfix small itemUnderHead">
        <ul class="list-inline text-muted pull-right">
            <?php if ($config['show_date']) { ?>
                <li class="itemPostDate dt-published">
                    <i class="fa fa-calendar"></i> <?php _e('Time'); ?>
                    : <?php echo $this->escape($story['time_publish_view']); ?>
                </li>
            <?php } ?>
            <?php if ($config['show_hits']) { ?>
                <li class="itemStats">
                    <i class="fa fa-eye"></i> <?php _e('Read'); ?>
                    : <?php echo _number($this->escape($story['hits'])); ?> <?php _e('Times'); ?>
                </li>
            <?php } ?>
            <?php if ($config['show_topic']) { ?>
                <li><i class="fa fa-folder"></i> <?php _e('Topics'); ?> :
                    <?php foreach ($story['topics'] as $storyTopic) { ?>
                        <span class=" p-category" itemprop="about">
                                        <a title="<?php echo $storyTopic['title']; ?>"
                                           href="<?php echo $storyTopic['url']; ?>"><?php echo $storyTopic['title']; ?></a>
                                    </span>
                    <?php } ?>
                </li>
            <?php } ?>
        </ul>
    </div>

    <div class="h-entry">
        <div class="clearfix">
            <div class="clearfix">
                <?php if (!empty($story['authors']) && $config['show_author']) { ?>
                    <div class="pull-left">
                        <?php foreach ($story['authors'] as $author) { ?>
                            <span class="p-author" itemprop="publisher"><?php echo $author['authorRole']; ?> : <a
                                    title="<?php echo $author['authorName']; ?>"
                                    href="<?php echo $author['authorUrl']; ?>"><?php echo $author['authorName']; ?></a></span>
                        <?php } ?>
                    </div>
                <?php } ?>
                <?php if ($config['show_topic']) { ?>
                    <div class="pull-left"><?php _e('Topics'); ?> :
                        <?php foreach ($story['topics'] as $storyTopic) { ?>
                            <span class=" p-category" itemprop="about"><a title="<?php echo $storyTopic['title']; ?>"
                                                                          href="<?php echo $storyTopic['url']; ?>"><?php echo $storyTopic['title']; ?></a></span>
                        <?php } ?>
                    </div>
                <?php } ?>
            </div>
            <?php if ($story['subtitle']) { ?>
                <div class="clearfix story-subtitle">
                    <p><?php echo $this->escape($story['subtitle']); ?></p>
                </div>
            <?php } ?>
            <?php if ($story['main_image'] || $story['additional_images']) { ?>
                <div class="gallery text-center col-md-12">
                    <div class="storyImageMain">
                        <div class="col-sm-12 col-md-12">
                            <div class="u-photo">
                                <?php $media = Pi::api('doc','media')->getSingleLinkData($story['main_image'], 'large', null, null, 'news') ?>
                                <a href="<?php echo $media['resized_url']; ?>"
                                   title="<?php echo $this->escape($story['title']); ?><?php if($media['copyright']) echo ' - ' . $media['copyright'] ?>">
                                    <img itemprop="image" class="img-responsive lazyload"
                                         src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
                                         data-src="<?php echo Pi::api('doc','media')->getSingleLinkUrl($story['main_image'])->setConfigModule('news')->thumb('medium'); ?>"
                                         alt="<?php echo $this->escape($story['title']); ?>"/>
                                </a>
                            </div>
                        </div>
                    </div>
                    <?php if (isset($story['additional_images']) && !empty($story['additional_images'])) { ?>
                        <div class="storyImageAttach">
                            <?php include $this->template('front/attach-image'); ?>
                        </div>
                    <?php } ?>
                </div>
            <?php } ?>
            <div class="storyText e-content" itemprop="description">
                <?php echo $story['text_description']; ?>
            </div>
            <?php if ($config['admin_text_extra'] && !empty($story['text_html'])) { ?>
                <div class="clearfix">
                    <?php echo $story['text_html']; ?>
                </div>
            <?php } ?>
            <div class="clearfix"></div>
            <?php include $this->template('front/attribute'); ?>
            <?php include $this->template('front/attribute-file'); ?>
            <?php include $this->template('front/tag'); ?>
            <?php include $this->template('front/attach'); ?>
            <div class="storyMedia">
                <?php include $this->template('front/attach-audio'); ?>
                <?php include $this->template('front/attribute-audio'); ?>
                <?php include $this->template('front/attach-video'); ?>
                <?php include $this->template('front/attribute-video'); ?>
            </div>
            <div class="clearfix">
                <div class="col-md-7 col-sm-10 col-xs-12">
                    <ul class="list-inline">
                        <li><?php if (!empty($vote)) {
                                include $this->template('votebar.phtml', 'front', 'vote');
                            } ?></li>
                        <li><?php if (!empty($favourite)) {
                                include $this->template('partial/favourite-loader', 'front');
                            } ?></li>
                    </ul>
                </div>
                <?php if ($config['social_sharing']) { ?>
                    <div class="col-md-5 col-sm-10 col-xs-12 socialSharing">
                        <?php echo $this->socialSharing(
                            $config['social_sharing'],
                            $this->escape($story['title']),
                            $this->escape($story['storyUrl']),
                            $this->escape($story['largeUrl'])
                        ); ?>
                    </div>
                <?php } ?>
            </div>
        </div>
    </div>
    <?php //if ($config['show_nav']) { ?>
    <div class="itemPager">
        <ul class="pager">
            <?php if (!empty($link['previous'])) { ?>
                <li class="previous"><a title="<?php echo $this->escape($link['previous']['title']); ?>"
                                        href="<?php echo $this->escape($link['previous']['url']); ?>"><?php _e('Previous'); ?></a>
                </li>
            <?php } ?>
            <?php if (!empty($link['next'])) { ?>
                <li class="next"><a title="<?php echo $this->escape($link['next']['title']); ?>"
                                    href="<?php echo $this->escape($link['next']['url']); ?>"><?php _e('Next'); ?></a>
                </li>
            <?php } ?>
        </ul>
    </div>
    <?php //} ?>
    <?php /* if (isset($relateds) && !empty($relateds)) { ?>
        <div class="itemList itemRelated">
            <h3><?php _e('Related storys'); ?></h3>
            <ul class="list-unstyled">
                <?php foreach ($relateds as $related) { ?>
                    <li><a title="<?php echo $this->escape($related['title']); ?>"
                           href="<?php echo $this->escape($related['storyUrl']); ?>"><?php echo $this->escape($related['title']); ?></a>
                    </li>
                <?php } ?>
            </ul>
        </div>
    <?php } */ ?>
</div>

<script>
    $(document).ready(function(){
        $('iframe').wrap('<div class="iframe-wrapper">');
    });
</script>