<?php
// Load front.css
$this->css($this->assetModule('css/front.css'), ['defer' => 'defer']);
// Image lightbox
if ($config['image_lightbox']) {
    $script
        = <<<'EOT'
window.addEventListener('DOMContentLoaded', function() {
    $('.gallery').each(function() {
        $(this).magnificPopup({
            delegate: 'a',
            type: 'image',
            gallery: {
                enabled:true
            }
        });
    });
});
EOT;
    $this->jQuery(['extension/jquery.magnific-popup.min.js' => ['defer' => 'defer']]);
    $this->jQuery('extension/magnific-popup.min.css', ['defer' => 'defer']);
    $this->footScript()->appendScript($script);
}
// Set Open Graph tags for meta
$this->doctype('HTML5');
$shareImage = (string) Pi::api('doc','media')->getSingleLinkUrl($story['main_image'])->setConfigModule('news')->thumb('large');
$this->headMeta($this->escape($story['storyUrl']), 'og:url', 'property');
$this->headMeta($story['title'], 'og:title', 'property');
if (isset($story['text_summary']) && !empty($story['text_summary'])) {
    $this->headMeta(_strip($story['text_summary']), 'og:description', 'property');
}
if ($shareImage) {
    $this->headMeta($shareImage, 'og:image', 'property');
}
// Set twitter for meta
$this->headMeta($this->escape($story['storyUrl']), 'twitter:url');
$this->headMeta($story['title'], 'twitter:title');
if (isset($story['text_summary']) && !empty($story['text_summary'])) {
    $this->headMeta(_strip($story['text_summary']), 'twitter:description');
}
if ($shareImage) {
    $this->headMeta($shareImage, 'twitter:image');
}

$this->js(Pi::url('static/vendor/lazysizes/lazysizes.min.js'), ['async' => 'async']);

?>
<div class="clearfix news-single-story" itemscope itemtype="https://schema.org/Article">
    <?php include $this->template('front/feed'); ?>
    <?php include $this->template('front/advertisement'); ?>

    <div class="clearfix page-header">
        <h1 class="p-name" itemprop="name headline">
            <?php if ($story['important']) { ?>
                <span class="badge badge-important">
					    <?php _e('Important'); ?>
				    </span>
            <?php } ?>
            <?php echo $this->escape($story['title']); ?>
        </h1>
    </div>

    <meta itemprop="datePublished" content="<?php echo $this->escape(date("Y-m-d H:i:s", $story['time_publish'])); ?>"/>
    <div class="clearfix small itemUnderHead">
        <ul class="list-inline text-muted float-right">
            <?php if ($config['show_date']) { ?>
                <li class="list-inline-item itemPostDate dt-published">
                    <i class="fas fa-calendar-alt"></i> <?php _e('Time'); ?>
                    : <?php echo $this->escape($story['time_publish_view']); ?>
                </li>
            <?php } ?>
            <?php if ($config['show_hits']) { ?>
                <li class="list-inline-item itemStats">
                    <i class="far fa-eye"></i> <?php _e('Read'); ?>
                    : <?php echo _number($this->escape($story['hits'])); ?> <?php _e('Times'); ?>
                </li>
            <?php } ?>
            <?php if ($config['show_topic']) { ?>
                <li class="list-inline-item"><i class="fas fa-folder"></i> <?php _e('Topics'); ?> :
                    <?php foreach ($story['topics'] as $storyTopic) { ?>
                        <span class=" p-category" itemprop="about">
                                        <a title="<?php echo $storyTopic['title']; ?>"
                                           href="<?php echo $storyTopic['url']; ?>"><?php echo $storyTopic['title']; ?></a>
                                    </span>
                    <?php } ?>
                </li>
            <?php } ?>
        </ul>
    </div>

    <div class="news-story-page clearfix h-entry">
        <?php if ($story['main_image'] || $story['additional_images']) { ?>
            <div class="gallery">
                <div class="storyImageMain">
                    <div class="thumbnail u-photo">
                        <?php $media = Pi::api('doc', 'media')->getSingleLinkData($story['main_image'], 'large', null, null, 'news') ?>
                        <a href="<?php echo $media['resized_url']; ?>"
                           title="<?php echo $this->escape($story['title']); ?><?php if ($media['copyright']) echo ' - ' . $media['copyright'] ?>">
                            <img itemprop="image" class="img-fluid lazyload"
                                 src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
                                 data-src="<?php echo Pi::api('doc', 'media')->getSingleLinkUrl($story['main_image'])->setConfigModule('news')->thumb(
                                     'medium'
                                 ); ?>"
                                 alt="<?php echo $this->escape($story['title']); ?>"/>
                        </a>
                    </div>
                </div>
                <?php if (isset($story['additional_images']) && !empty($story['additional_images'])) { ?>
                    <div class="storyImageAttach row">
                        <?php include $this->template('front/attach-image'); ?>
                    </div>
                <?php } ?>
            </div>
        <?php } ?>
        <?php if ($story['subtitle']) { ?>
            <div class="clearfix story-subtitle">
                <p><?php echo $this->escape($story['subtitle']); ?></p>
            </div>
        <?php } ?>
        <div class="clearfix p-summary" itemprop="description">
            <?php echo $story['text_summary']; ?>
        </div>
        <div class="clearfix e-content" itemprop="description">
            <?php echo $story['text_description']; ?>
        </div>
        <?php if ($config['admin_text_extra'] && !empty($story['text_html'])) { ?>
            <div class="clearfix">
                <?php echo $story['text_html']; ?>
            </div>
        <?php } ?>
        <div class="storyMedia clearfix">
            <?php include $this->template('front/attach-audio'); ?>
            <?php include $this->template('front/attribute-audio'); ?>
            <?php include $this->template('front/attach-video'); ?>
            <?php include $this->template('front/attribute-video'); ?>
            <?php include $this->template('front/attribute-file'); ?>
            <?php include $this->template('front/attach'); ?>
        </div>
        <?php if ($config['show_nav']) { ?>
            <div class="itemPager">
                <ul class="pagination">
                    <?php if (!empty($link['previous'])) { ?>
                        <li class="previous page-item"><a class="page-link" title="<?php echo $this->escape($link['previous']['title']); ?>"
                                                          href="<?php echo $this->escape($link['previous']['url']); ?>"><?php _e('Previous'); ?></a>
                        </li>
                    <?php } ?>
                    <?php if (!empty($link['next'])) { ?>
                        <li class="next page-item"><a class="page-link" title="<?php echo $this->escape($link['next']['title']); ?>"
                                                      href="<?php echo $this->escape($link['next']['url']); ?>"><?php _e('Next'); ?></a>
                        </li>
                    <?php } ?>
                </ul>
            </div>
        <?php } ?>
        <div class="clearfix">
            <ul class="list-inline">
                <li class="list-inline-item"><?php if (!empty($vote)) {
                        include $this->template('votebar.phtml', 'front', 'vote');
                    } ?></li>
                <li class="list-inline-item"><?php if (!empty($favourite)) {
                        include $this->template('partial/favourite-loader', 'front');
                    } ?></li>
            </ul>
        </div>
        <?php if (!empty($story['authors']) && $config['show_author']) { ?>
            <div class="clearfix">
                <?php foreach ($story['authors'] as $author) { ?>
                    <div class="p-author clearfix" itemprop="publisher">
                        <p class="text-center">
                            <img itemprop="image" class="rounded-circle"
                                 src="<?php echo $this->escape($author['authorThumbUrl']); ?>"
                                 alt="<?php echo $this->escape($author['authorName']); ?>"/>
                        </p>

                        <p class="text-center">
                            <?php echo $this->escape($author['authorRole']); ?> :
                            <a title="<?php echo $this->escape($author['authorName']); ?>"
                               href="<?php echo $this->escape($author['authorUrl']); ?>">
                                <?php echo $this->escape($author['authorName']); ?>
                            </a>
                        </p>
                    </div>
                <?php } ?>
            </div>
        <?php } ?>
        <?php if ($config['show_tag'] && isset($tag) && !empty($tag)) { ?>
            <div class="card bg-light mb-3 clearfix">
                <h2><?php _e('Tags'); ?></h2>
                <ul class="tagList list-inline">
                    <?php foreach ($tag as $term) { ?>
                        <li class="list-inline-item tagItem">
                            <a title="<?php echo $this->escape($term); ?>"
                               href="<?php echo Pi::url($this->url('', ['controller' => 'tag', 'action' => 'term', 'slug' => urlencode($term)])); ?>">
                                <i class="fas fa-tag"></i> <?php echo $this->escape($term); ?>
                            </a>
                        </li>
                    <?php } ?>
                </ul>
            </div>
        <?php } ?>
        <?php include $this->template('front/attribute'); ?>
        <?php if ($config['social_sharing']) { ?>
            <div class="clearfix">
                <div class="col-md-12 col-sm-12 col-12 socialSharingText">
                    <strong><?php _e('Share if you like'); ?></strong>
                </div>
                <div class="col-md-12 col-sm-12 col-12 socialSharing">
                    <?php echo $this->socialSharing(
                        $config['social_sharing'],
                        $this->escape($story['title']),
                        $this->escape($story['storyUrl']),
                        $this->escape($story['largeUrl'])
                    ); ?>
                </div>
            </div>
        <?php } ?>
        <?php if (isset($relateds) && !empty($relateds)) { ?>
            <div class="card bg-light mb-3 news-story-related">
                <div class="card-heading">
                    <?php _e('Related storys'); ?>
                </div>
                <div class="list-group">
                    <?php foreach ($relateds as $related) { ?>
                        <div class="list-group-item clearfix" itemscope itemtype="https://schema.org/Article">
                            <div class="row">
                                <div class="col-md-4">
                                    <?php if ($related['main_image']) { ?>
                                        <img itemprop="image" class="img-fluid u-photo lazyload"
                                             src="data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw=="
                                             data-src="<?php echo $this->escape($related['thumbUrl']); ?>"
                                             alt="<?php echo $this->escape($related['title']); ?>"/>
                                    <?php } ?>
                                </div>
                                <div class="col-md-8">
                                    <a itemprop="url" class="u-url" title="<?php echo $this->escape($related['title']); ?>"
                                       href="<?php echo $this->escape($related['storyUrl']); ?>">
                                        <span class="p-name" itemprop="name headline"><?php echo $this->escape($related['title']); ?></span>
                                    </a>
                                    <meta itemprop="datePublished" content="<?php echo $this->escape(date("Y-m-d H:i:s", $related['time_publish'])); ?>"/>
                                </div>
                            </div>
                        </div>
                    <?php } ?>
                </div>
            </div>
        <?php } ?>
    </div>
</div>

<script>
    $(document).ready(function () {
        $('iframe').wrap('<div class="iframe-wrapper">');
    });
</script>