<?php if ($config['show_tag'] && isset($tag) && !empty($tag)) { ?>
    <div class="clearfix tagList">
        <?php foreach ($tag as $term) { ?>
            <span class="tagItem">
                <a title="<?php echo $this->escape($term); ?>"
                   href="<?php echo Pi::url($this->url('', ['controller' => 'tag', 'action' => 'term', 'slug' => urlencode($term)])); ?>"><i
                            class="fas fa-tag"></i> <?php echo $this->escape($term); ?></a>
            </span>
        <?php } ?>
    </div>
<?php } ?>