<?php if ($config['show_tag'] && isset($tag) && !empty($tag)) { ?>
<div class="tagbar">
<?php foreach($tag as $term) { ?>
	<span class="label label-default">
		<a title="<?php echo $this->escape($term); ?>" href="<?php echo $this->url('', array('controller' => 'tag', 'action' => 'term', 'slug' => urldecode($term))); ?>"><i class="fa fa-tag"></i> <?php echo $this->escape($term); ?></a>
	</span>
<?php } ?>
</div>
<?php } ?>