<?php
$this->css($this->assetModule('css/front.css'), ['defer' => 'defer']);
// Set Open Graph tags for meta
$this->doctype('HTML5');
$this->headMeta(Pi::url($this->url('', ['module' => 'news', 'controller' => 'topic'])), 'og:url', 'property');
$this->headMeta(__('List of all topics'), 'og:title', 'property');
$this->headMeta(__('List of all topics'), 'og:description', 'property');
// Set twitter for meta
$this->headMeta(Pi::url($this->url('', ['module' => 'news', 'controller' => 'topic'])), 'twitter:url');
$this->headMeta(__('List of all topics'), 'twitter:title');
$this->headMeta(__('List of all topics'), 'twitter:description');
?>
<div class="clearfix h-entry" itemtype="https://schema.org/ItemList">
    <?php include $this->template('front/feed'); ?>
    <div class="page-header">
        <h1><?php _e('Topic list'); ?></h1>
    </div>
    <?php if (isset($topics) && !empty($topics)) { ?>
        <div class="topics clearfix">
            <?php foreach ($topics as $topic) { ?>
                <div class="col-12 col-sm-6 col-md-3" itemprop="itemListElement">
                    <div class="thumbnail">
                        <?php if (!empty($topic['image'])) { ?>
                            <a itemprop="url" href="<?php echo $this->escape($topic['topicUrl']); ?>"
                               title="<?php echo $this->escape($topic['title']); ?>">
                                <img itemprop="image" class="u-photo"
                                     src="<?php echo $this->escape($topic['mediumUrl']); ?>"
                                     alt="<?php echo $this->escape($topic['title']); ?>">
                            </a>
                        <?php } ?>
                        <div class="caption">
                            <a itemprop="url" href="<?php echo $this->escape($topic['topicUrl']); ?>"
                               title="<?php echo $this->escape($topic['title']); ?>">
                                <h3 itemprop="name" class="p-name"><?php echo $this->escape($topic['title']); ?></h3>
                            </a>
                        </div>
                    </div>
                </div>
            <?php } ?>
        </div>
    <?php } else { ?>
        <div class="alert alert-warning" role="alert">
            <?php _e('No topic has been made on this part yet. please check this page later'); ?>
        </div>
    <?php } ?>
</div>