<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="news">
	<?php if(!empty($config['advertisement'])) { ?><div class="itemAds"><?php echo $config['advertisement']; ?></div><?php } ?>
	<div class="newsTopic">
		<table class="table table-striped table-bordered table-condensed">
			<thead>
				<th><?php _e('List of Topics'); ?></th>
			</thead>
			<tbody>
				<?php foreach($topics as $topic) { ?>
				<tr>
					<td class="top">
						<div class="itemTitle"><a title="<?php echo $topic['title']; ?>" href="<?php echo $this->url('.news', array('module' => $module ,'controller' => 'topic' ,'slug' => $this->escape($topic['slug']))); ?>"><?php echo $this->escape($topic['title']); ?></a></div>
						<div class="itemText"><?php echo $topic['body']; ?></div>
						<?php if($topic['image']){ ?>
						<div class="gallery">
							<a href="<?php echo $topic['mediumurl']; ?>" title="<?php echo $this->escape($topic['title']); ?>" >
								<img class="<?php echo $config['imgfloat']; ?> story_img" src="<?php echo $topic['thumburl']; ?>" alt="<?php echo $this->escape($topic['title']); ?>" />
							</a>
						</div>
						<?php } ?>
					</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
	<div class="paginator"></div>
</div>