<?php if($topic['show_topicinfo'] && (!empty($topic['description']) || !empty($topic['image']))) { 
if($config['image_lightbox']){ 
	$this->jQuery();
	$this->js($this->assetModule('js/lightbox.js'));
	$this->footScript()->appendScript("$(function() {
		$('.gallery a').lightBox({
	        imageLoading: '" . $this->assetModule('image/lightbox-ico-loading.gif') ."',
	        imageBtnClose:'" . $this->assetModule('image/lightbox-btn-close.gif') ."',
	        imageBtnNext:'" . $this->assetModule('image/lightbox-btn-next.gif') ."',
	        imageBtnPrev:'" . $this->assetModule('image/lightbox-btn-prev.gif') ."',
	        imageBlank:'" . $this->assetModule('image/lightbox-blank.gif') ."',
	        overlayOpacity: 0.6,
		    containerResizeSpeed: 350,
		});
	});");
	$this->css($this->assetModule('css/lightbox.css'));
} 
?>
<div class="topicinfo">
	<div class="panel panel-default">
  		<div class="panel-heading"><?php echo $this->escape($topic['title']); ?></div>
		<div class="panel-body">
			<?php if(!empty($topic['image'])) {  ?>
			<div class="pull-left gallery itemImageList">
		   		<?php if($config['image_lightbox']){ ?>
				<a href="<?php echo $topic['mediumUrl']; ?>" title="<?php echo $this->escape($topic['title']); ?>">
					<img class="ItemStoryImg img-thumbnail" src="<?php echo $topic['thumbUrl']; ?>" alt="<?php echo $this->escape($topic['title']); ?>" />
				</a>
				<?php } else { ?>
				<img class="ItemStoryImg img-thumbnail" src="<?php echo $topic['thumbUrl']; ?>" alt="<?php echo $this->escape($topic['title']); ?>" />
				<?php } ?>
			</div>
			<?php } ?>  
			<?php echo $topic['description']; ?>
		</div>
	</div>
</div>
<?php } ?>