<?php 
if($topic['showtopicinfo'] && (!empty($topic['body']) || !empty($topic['image']))) { 
	if($config['image_lightbox'] && !empty($topic['image'])){ 
		$this->jQuery();
		$this->js($this->assetModule('js/lightbox.js'));
		$this->footScript()->appendScript("$(function() {
			  $('.gallery a').lightBox({
		        imageLoading: '" . $this->assetModule('image/lightbox-ico-loading.gif') . "',
		        imageBtnClose:'" . $this->assetModule('image/lightbox-btn-close.gif') . "',
		        imageBtnNext:'" . $this->assetModule('image/lightbox-btn-next.gif') . "',
		        imageBtnPrev:'" . $this->assetModule('image/lightbox-btn-prev.gif') . "',
		        imageBlank:'" . $this->assetModule('image/lightbox-blank.gif') . "',
		        overlayOpacity: 0.6,
			     containerResizeSpeed: 350,
			  });
		});");
		$this->css($this->assetModule('css/lightbox.css'));
	} 
?>
<div class="topicinfo page-header">
	<div class="media">
		<?php if(!empty($topic['image'])) {  ?>
		<div class="pull-left gallery itemImageList">
		   <?php if($config['image_lightbox']){ ?>
			<a href="<?php echo $topic['mediumurl']; ?>" title="<?php echo $this->escape($topic['title']); ?>">
				<img class="media-object ItemStoryImg img-polaroid" src="<?php echo $topic['thumburl']; ?>" alt="<?php echo $this->escape($topic['title']); ?>" />
			</a>
			<?php } else { ?>
			<img class="media-object ItemStoryImg img-polaroid" src="<?php echo $topic['thumburl']; ?>" alt="<?php echo $this->escape($topic['title']); ?>" />
			<?php } ?>
		</div>
		<?php } ?>
		<div class="media-body">
			<h4 class="media-heading"><?php echo $this->escape($topic['title']); ?></h4>
			<?php echo $topic['body']; ?>
		</div>
	</div>
</div>
<?php } ?>