<?php $this->css($this->assetModule('css/front.css')); ?>
<div class="news">
	<?php include $this->template('front/feed'); ?>
	<?php include $this->template('front/advertisement'); ?>
	<div class="topic-list">
		<table class="table table-striped table-bordered table-condensed">
			<thead>
				<th><?php _e('List of Topics'); ?></th>
			</thead>
			<tbody>
				<?php foreach($topics as $topic) { ?>
				<tr>
					<td class="top">
						<?php if($topic['image']){ ?>
						<img class="img-thumbnail pull-right" src="<?php echo $this->escape($topic['thumbUrl']); ?>" alt="<?php echo $this->escape($topic['title']); ?>" />
						<?php } ?>
						<h4><a title="<?php echo $this->escape($topic['title']); ?>" href="<?php echo $this->escape($topic['topicUrl']); ?>"><?php echo $this->escape($topic['title']); ?></a></h4>
						<?php echo $topic['description']; ?>
					</td>
				</tr>
				<?php } ?>
			</tbody>
		</table>
	</div>
</div>