<?php
$this->css($this->assetModule('css/front.css'), ['defer' => 'defer']);
// Set Open Graph tags for meta
$this->doctype('HTML5');
$this->headMeta(Pi::url($this->url('', ['module' => 'news', 'controller' => 'topic'])), 'og:url', 'property');
$this->headMeta(__('List of all topics'), 'og:title', 'property');
$this->headMeta(__('List of all topics'), 'og:description', 'property');
// Set twitter for meta
$this->headMeta(Pi::url($this->url('', ['module' => 'news', 'controller' => 'topic'])), 'twitter:url');
$this->headMeta(__('List of all topics'), 'twitter:title');
$this->headMeta(__('List of all topics'), 'twitter:description');
?>
<div class="clearfix h-entry" itemtype="https://schema.org/ItemList">
    <div class="page-header">
        <h1><?php _e('Topic list'); ?></h1>
    </div>
    <?php if (isset($topics) && !empty($topics)) { ?>
        <div class="clearfix row">
            <?php foreach ($topics as $topic) { ?>
                <div class="col-12 col-md-4 col-lg-4">
                    <div class="card h-entry mb-3 text-center text-justify" itemprop="itemListElement">
                        <?php if ($topic['main_image']) { ?>
                            <a itemprop="url" title="<?php echo $this->escape($topic['title']); ?>" href="<?php echo $this->escape($topic['topicUrl']); ?>">
                                <img class="card-img-top" itemprop="image" src="<?php echo $this->escape($topic['thumbUrl']); ?>" alt="<?php echo $this->escape($topic['title']); ?>"/>
                            </a>
                        <?php } ?>
                        <div class="card-body">
                            <h2 class="card-title p-name mb-3" itemprop="name">
                                <a itemprop="url" title="<?php echo $this->escape($topic['title']); ?>" href="<?php echo $this->escape($topic['topicUrl']); ?>">
                                    <?php echo $this->escape($topic['title']); ?>
                                </a>
                            </h2>
                            <?php if (isset($topic['text_summary']) && !empty($topic['text_summary'])) { ?>
                                <div class="card-text clearfix mb-3">
                                    <?php echo $topic['text_summary']; ?>
                                </div>
                            <?php } ?>
                            <a href="<?php echo $this->escape($topic['topicUrl']); ?>" class="btn btn-link">
                                <?php _e('Read stories'); ?>
                            </a>
                        </div>
                    </div>
                </div>
            <?php } ?>
        </div>
    <?php } else { ?>
        <div class="alert alert-warning" role="alert">
            <?php _e('No topic has been made on this part yet. please check this page later'); ?>
        </div>
    <?php } ?>
</div>