<?php 
$this->css(array(
	$this->assetModule('css/profile.css'),
	$this->assetModule('css/front.css'),
)); 
?>
<div class="news">
	<?php if(!empty($config['advertisement'])){ ?><div class="itemAds"><?php echo $config['advertisement']; ?></div><?php } ?>
	<div class="newsWriter">
		<h2><?php _e('List of Writers'); ?></h2>
		<div class="well">
			<?php foreach($writers as $writer) { ?>
			<div class="profile">
				<div class="profile-avatar">
					<?php echo $this->gravatar($this->escape($writer['email'])); ?>
				</div>
				<div class="profile-info">
					<h5 class="profile-identity"><?php echo $this->escape($writer['identity']); ?></h5>
					<div class="profile-email"><?php echo $this->escape($writer['email']); ?></div>
					<div class="profile-link"><a title="<?php _e('All stores'); ?>" href="<?php echo $this->url('.news', array('module' => $module ,'controller' => 'writer' ,'action' => 'index' ,'slug' => $this->escape($writer['identity']))); ?>"><?php _e('All stores'); ?></a></div>
				</div>
				<div class="clearfix"></div>
			</div>
			<?php } ?>
		</div>
	</div>
</div>