<?php 
$this->css(array(
	$this->assetModule('css/profile.css'),
	$this->assetModule('css/front.css'),
)); 
?>
<div class="news">
	<?php include $this->template('front/feed'); ?>
	<?php include $this->template('front/advertisement'); ?>
	<div class="newsWriter">
		<h2><?php _e('List of Writers'); ?></h2>
		<div class="well">
			<?php foreach($writers as $writer) { ?>
			<div class="profile">
				<div class="profile-avatar">
					<?php echo $this->escape($writer['avatar']); ?>
				</div>
				<div class="profile-info">
					<h5 class="profile-identity"><?php echo $this->escape($writer['name']); ?></h5>
					<div class="profile-email"><?php echo $this->escape($writer['email']); ?></div>
					<div class="profile-link">
						<a title="<?php _e('All stores'); ?>" href="<?php echo $this->escape($writer['url']); ?>"><?php _e('All stores'); ?></a>
					</div>
				</div>
				<div class="clearfix"></div>
			</div>
			<?php } ?>
		</div>
	</div>
</div>